cpp_quote("#include <winapifamily.h>")

#pragma region Application Family
cpp_quote("#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)")

import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";

cpp_quote("#if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)")

// Interfaces 
[object, uuid(407fb1de-f85a-4150-97cf-b7fb274fb4f8)]
interface IInkD2DRenderer : IUnknown
{
    HRESULT Draw([in] IUnknown *pD2D1DeviceContext,
                 [in] IUnknown *pInkStrokeIterable,
                 [in] BOOL fHighContrast);
}

[uuid(390d0ab0-19e2-46bb-862e-b09f3cdcf8b9)]
library InkD2DRendererLib
{
    [uuid(4044e60c-7b01-4671-a97c-04e0210a07a5)]
    coclass InkD2DRenderer
    {
        [default] interface IInkD2DRenderer;
    }
};

cpp_quote("#endif // NTDDI_VERSION >= NTDDI_WINTHRESHOLD")

cpp_quote("#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP) */")
#pragma endregion