//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of your Microsoft Windows CE
// Source Alliance Program license form.  If you did not accept the terms of
// such a license, you are not authorized to use this source code.
//


#pragma once

static const HRESULT ZERROR_E_NOTINITIALIZED           = (HRESULT)0x803A0000;
static const HRESULT ZERROR_E_NODATA                   = (HRESULT)0x803A0001;
static const HRESULT ZERROR_E_NOTFOUND                 = (HRESULT)0x803A0002;
static const HRESULT ZERROR_E_NOTOPEN                  = (HRESULT)0x803A0003;
static const HRESULT ZERROR_E_ALREADYOPEN              = (HRESULT)0x803A0004;
static const HRESULT ZERROR_E_MULTIPLE_OWNER_MCARDS    = (HRESULT)0x803A0005;
static const HRESULT ZERROR_E_OUTOFDATE                = (HRESULT)0x803A0006;
static const HRESULT ZERROR_E_DRM                      = (HRESULT)0x803A0007;
static const HRESULT ZERROR_E_DRMLICENSEEXPIRED        = (HRESULT)0x803A0008;
static const HRESULT ZERROR_E_DRMPLAYCOUNTEXPIRED      = (HRESULT)0x803A0009;
static const HRESULT ZERROR_E_UNSUPPORTEDCONTENT       = (HRESULT)0x803A000A;
static const HRESULT ZERROR_E_UNSUPPORTEDATTR          = (HRESULT)0x803A000B;
static const HRESULT ZERROR_E_DATABASEFULL             = (HRESULT)0x803A000C;
static const HRESULT ZERROR_E_TASKQUEUEFULL            = (HRESULT)0x803A000D;
static const HRESULT ZERROR_E_NOMORECHAPTERS           = (HRESULT)0x803A000E;
static const HRESULT ZERROR_E_CONTENTEXPLICIT          = (HRESULT)0x803A000F;
static const HRESULT ZERROR_E_STREAMNOTAVAILABLE       = (HRESULT)0x803A0010;
static const HRESULT ZERROR_E_DEVICE_NOTAUDIBLEACTIVATED = (HRESULT)0x803A0011;
static const HRESULT ZERROR_E_MESSAGE_TOO_LARGE        = (HRESULT)0x803A0012;
static const HRESULT ZERROR_E_DRMTVFAILURE             = (HRESULT)0x803A0013;

// Begin WM7 zerrors
static const HRESULT ZERROR_E_NO_STREAM                = (HRESULT)0x803A0080;
static const HRESULT ZERROR_E_READ_JIBBER_JABBER       = (HRESULT)0x803A0081;
static const HRESULT ZERROR_E_INVALID_FEED             = (HRESULT)0x803A0082;
static const HRESULT ZERROR_E_NOCURRENTITEM            = (HRESULT)0x803A0083;
static const HRESULT ZERROR_E_YOUR_DIR_IS_A_FILE       = (HRESULT)0x803A0084;
static const HRESULT ZERROR_E_CREATE_DIR_LIED          = (HRESULT)0x803A0085;
static const HRESULT ZERROR_E_ZLIB_UNHAPPY             = (HRESULT)0x803A0086;
static const HRESULT ZERROR_E_ZLIB_STREAM_TOO_SHORT    = (HRESULT)0x803A0087;
static const HRESULT ZERROR_E_STORAGE                  = (HRESULT)0x803A0088;
static const HRESULT ZERROR_E_WINMO_UNSUPPORTED_QUEUE  = (HRESULT)0x803A0089;
static const HRESULT ZERROR_E_WRITE_ACCESS_DENIED      = (HRESULT)0x803A008A;
static const HRESULT ZERROR_E_URL_FETCH_TIMEOUT        = (HRESULT)0x803A00C0;
static const HRESULT ZERROR_E_TOO_MANY_CLIENT_QUEUES   = (HRESULT)0x803A00D0;
static const HRESULT ZERROR_E_QUEUE_NOT_ALLOCATED      = (HRESULT)0x803A00D1;
static const HRESULT ZERROR_E_NO_URL_PARAMS            = (HRESULT)0x803A00D3;
static const HRESULT ZERROR_E_BAD_SMARTDJ_STORE        = (HRESULT)0x803A00D4;
static const HRESULT ZERROR_E_DB_GENERATION_MISMATCH   = (HRESULT)0x803A00D5;
static const HRESULT ZERROR_E_SMARTDJ_ARTIST_TOO_FREQUENT           = (HRESULT)0x803A00D6;
static const HRESULT ZERROR_E_SMARTDJ_SONG_TOO_SHORT                = (HRESULT)0x803A00D7;
static const HRESULT ZERROR_E_SMARTDJ_USER_HATES_SONG               = (HRESULT)0x803A00D8;
static const HRESULT ZERROR_E_SMARTDJ_SONG_ALREADY_ADDED            = (HRESULT)0x803A00D9;
static const HRESULT ZERROR_E_SMARTDJ_EXPLICIT_SONG_NOT_ALLOWED     = (HRESULT)0x803A00DA;
static const HRESULT ZERROR_E_SMARTDJ_ONLINE_SONG_IS_SO_LAST_WEEK   = (HRESULT)0x803A00DB;
static const HRESULT ZERROR_E_SMARTDJ_NO_MARKETPLACE_MIX_FOR_ARTIST = (HRESULT)0x803A00DC;
static const HRESULT ZERROR_E_SMARTDJ_NO_MARKETPLACE_ID_FOR_SEED    = (HRESULT)0x803A00DD;
static const HRESULT ZERROR_E_SMARTDJ_NO_VECTOR_FOR_SEED            = (HRESULT)0x803A00DE;
static const HRESULT ZERROR_E_SMARTDJ_NO_MATCHES_FOR_SEED           = (HRESULT)0x803A00DF;

// Begin Mango zerrors
static const HRESULT ZERROR_E_ZMDBGENERALFAIL          = (HRESULT)0x803A00C1;
static const HRESULT ZERROR_E_ZMDB_BLOCKUNPINNED       = (HRESULT)0x803A00C2;
static const HRESULT ZERROR_E_ZMDB_INVALIDBLOCKOFFSET  = (HRESULT)0x803A00C3;
static const HRESULT ZERROR_E_INVALID_ATTR_VALUE       = (HRESULT)0x803A00C4;
static const HRESULT ZERROR_E_ZMDB_FAILEDBLOCKINTEGRITY= (HRESULT)0x804A00C5;
static const HRESULT ZERROR_E_ZMDB_MIGRATION_NEEDED    = (HRESULT)0x804A00C6;
static const HRESULT ZERROR_E_ALREADYEXISTS            = (HRESULT)0x803A00C7;

static const HRESULT ZERROR_E_UNEXPECTED_WIN32_ERROR   = (HRESULT)0x803A0FFF;

static const HRESULT ZERROR_E_INSUFFICIENT_BUFFER      = (HRESULT)0x8007007A;  // 0x7A = 122L = ERROR_INSUFFICIENT_BUFFER
static const HRESULT ZERROR_E_ACCESS_DENIED            = (HRESULT)0x80070005;  // 0x05 = 5L = ERROR_ACCESS_DENIED
static const HRESULT ZERROR_E_NOMORE                   = (HRESULT)0x80070103;  // 0x103 = 259L = ERROR_NO_MORE_ITEMS


// Apollo
static const HRESULT ZERROR_E_INVALID_SERVICE_HANDLE                 = (HRESULT)0x803A00E0;
static const HRESULT ZERROR_E_CALL_MADE_FROM_RPC_THREAD              = (HRESULT)0x803A00E1;
static const HRESULT ZERROR_E_THREAD_ALREADY_HAS_ACTIVE_RPC_CONTEXT  = (HRESULT)0x803A00E2;
static const HRESULT ZERROR_E_THREAD_HAS_NO_ACTIVE_RPC_CONTEXT       = (HRESULT)0x803A00E3;
static const HRESULT ZERROR_E_INVALID_LIST_HANDLE                    = (HRESULT)0x803A00E4;
static const HRESULT ZERROR_E_NO_FREE_LIST_HANDLES                   = (HRESULT)0x803A00E5;
static const HRESULT ZERROR_E_SPECIAL_FOLDER_DELETE_ACCESS_DENIED    = (HRESULT)0x803A00E6;
static const HRESULT ZERROR_E_FOLDER_DELETE_NOT_EMPTY                = (HRESULT)0x803A00E7;
static const HRESULT ZERROR_E_WNF_SUBSCRIBE_FAILURE                  = (HRESULT)0x803A00E8;
static const HRESULT ZERROR_E_WNF_COULDNT_REGISTER_GLOBAL_STATE_NAME = (HRESULT)0x803A00E9;
static const HRESULT ZERROR_E_WNF_PUBLISH_FAILURE                    = (HRESULT)0x803A00EA;
static const HRESULT ZERROR_E_ALREADY_INITIALIZED                    = (HRESULT)0x803A00EB;
static const HRESULT ZERROR_E_USER_DECLINED_DELETE                   = (HRESULT)0x803A00EC;
static const HRESULT ZERROR_E_UNSUPPORTED_IMAGE_TYPE                 = (HRESULT)0x803A00ED;
static const HRESULT ZERROR_E_RECEIPTCACHECORRUPT                    = (HRESULT)0x803A00EE;
static const HRESULT ZERROR_E_RECEIPTFILEWRITEFAILED                 = (HRESULT)0x803A00EF;
static const HRESULT ZERROR_E_BAD_SONG_METADATA                      = (HRESULT)0x803A00F0;
//static const HRESULT ZERROR_E_unused                               = (HRESULT)0x803A00F1;
static const HRESULT ZERROR_E_BLOCK_BIGGER_THAN_PAGE_SIZE            = (HRESULT)0x803A00F2;
