/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name: IddTraceEnums.h

Abstract:
    Generated trace enums

Environment:
    kernel mode only

--*/

#ifndef _IDDTRACEENUMS_H_
#define _IDDTRACEENUMS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

// begin_wpp config
// CUSTOM_TYPE(IDDCX_FEATURE_IMPLEMENTATION, ItemEnum(_IDDCX_FEATURE_IMPLEMENTATION));
// CUSTOM_TYPE(IDDCX_TRANSMISSION_TYPE, ItemEnum(_IDDCX_TRANSMISSION_TYPE));
// CUSTOM_TYPE(IDDCX_ADAPTER_FLAGS, ItemEnum(_IDDCX_ADAPTER_FLAGS));
// CUSTOM_TYPE(IDDCX_MONITOR_DESCRIPTION_TYPE, ItemEnum(_IDDCX_MONITOR_DESCRIPTION_TYPE));
// CUSTOM_TYPE(IDDCX_MONITOR_MODE_ORIGIN, ItemEnum(_IDDCX_MONITOR_MODE_ORIGIN));
// CUSTOM_TYPE(IDDCX_UPDATE_REASON, ItemEnum(_IDDCX_UPDATE_REASON));
// CUSTOM_TYPE(IDDCX_PATH_FLAGS, ItemEnum(_IDDCX_PATH_FLAGS));
// CUSTOM_TYPE(IDDCX_XOR_CURSOR_SUPPORT, ItemEnum(_IDDCX_XOR_CURSOR_SUPPORT));
// CUSTOM_TYPE(IDDCX_CURSOR_SHAPE_TYPE, ItemEnum(_IDDCX_CURSOR_SHAPE_TYPE));
// CUSTOM_TYPE(IDDCX_FRAME_STATUS, ItemEnum(_IDDCX_FRAME_STATUS));
// CUSTOM_TYPE(IDDCX_FRAME_STATISTICS_STEP_TYPE, ItemEnum(_IDDCX_FRAME_STATISTICS_STEP_TYPE));
// CUSTOM_TYPE(IDDCX_FRAME_STATISTICS_FLAGS, ItemEnum(_IDDCX_FRAME_STATISTICS_FLAGS));
// CUSTOM_TYPE(IDDCX_GAMMARAMP_TYPE, ItemEnum(_IDDCX_GAMMARAMP_TYPE));
// end_wpp

WDF_EXTERN_C_END

#endif // _IDDTRACEENUMS_H_

