/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmCx.h

Abstract:

    Main header file for USB Connector Manager class extension client.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMCX_H_
#define _UCMCX_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START




typedef VOID (*UCMFUNC) (VOID);
extern UCMFUNC UcmFunctions[];

#include "UcmTypes.h"
#include "UcmGlobals.h"
#include "UcmFuncEnum.h"
#include "UcmManager.h"





WDF_EXTERN_C_END

#endif // _UCMCX_H_

