

/* this ALWAYS GENERATED file contains the definitions for the interfaces */


 /* File created by MIDL compiler version 8.01.0618 */
/* @@MIDL_FILE_HEADING(  ) */



/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include "rpc.h"
#include "rpcndr.h"

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */


#ifndef __zmedialibtypes_h__
#define __zmedialibtypes_h__

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/* Forward Declarations */ 

/* header files for imported files */
#include "wtypes.h"
#include "oaidl.h"

#ifdef __cplusplus
extern "C"{
#endif 


/* interface __MIDL_itf_zmedialibtypes_0000_0000 */
/* [local] */ 

typedef unsigned int size_t;

typedef ULONG HZMEDIALIST;

typedef ULONG HZMEDIAWORKITEM;

typedef ULONG ZMEDIAITEM;

typedef ULONG ZMEDIAITEMSTREAM;

typedef 
enum _ZMEDIAITEM_TYPE
    {
        ZMEDIAITEM_TYPE_INVALID	= 0,
        ZMEDIAITEM_TYPE_AUDIO	= 0x1,
        ZMEDIAITEM_TYPE_VIDEO	= 0x2,
        ZMEDIAITEM_TYPE_PICTURE	= 0x3,
        ZMEDIAITEM_TYPE_UNKNOWN	= 0x4,
        ZMEDIAITEM_TYPE_FOLDER	= 0x5,
        ZMEDIAITEM_TYPE_ALBUM	= 0x6,
        ZMEDIAITEM_TYPE_PLAYLIST	= 0x7,
        ZMEDIAITEM_TYPE_ARTIST	= 0x8,
        ZMEDIAITEM_TYPE_AUDIOGENRE	= 0x9,
        ZMEDIAITEM_TYPE_VIDEOSERIES	= 0xa,
        ZMEDIAITEM_TYPE_DATERANGE	= 0xb,
        ZMEDIAITEM_TYPE_PICTUREALBUM	= 0xc,
        ZMEDIAITEM_TYPE_USERCARD	= 0xd,
        ZMEDIAITEM_TYPE_INBOXMSG	= 0xe,
        ZMEDIAITEM_TYPE_PODCASTSERIES	= 0xf,
        ZMEDIAITEM_TYPE_PODCASTAUDIO	= 0x10,
        ZMEDIAITEM_TYPE_AUDIOBOOK	= 0x11,
        ZMEDIAITEM_TYPE_AUDIOBOOKPART	= 0x12,
        ZMEDIAITEM_TYPE_GAME	= 0x13,
        ZMEDIAITEM_TYPE_GAMERUNTIME	= 0x14,
        ZMEDIAITEM_TYPE_GAMESTORAGE	= 0x15,
        ZMEDIAITEM_TYPE_CLOUDTASK	= 0x16,
        ZMEDIAITEM_TYPE_CLOUDJOB	= 0x17,
        ZMEDIAITEM_TYPE_CARTENTRY	= 0x18,
        ZMEDIAITEM_TYPE_QUICKLAUNCH_ITEM	= 0x19,
        ZMEDIAITEM_TYPE_BOOKMARK	= 0x1a,
        ZMEDIAITEM_TYPE_RADIOPRESET	= 0x1b,
        ZMEDIAITEM_TYPE_EVENT	= 0x1c,
        ZMEDIAITEM_TYPE_LETTER	= 0xfb,
        ZMEDIAITEM_TYPE_TRANSIENTPICTURE	= 0xfc,
        ZMEDIAITEM_TYPE_TRANSIENTAUDIO	= 0xfd,
        ZMEDIAITEM_TYPE_FIRMWARE	= 0xfe,
        ZMEDIAITEM_TYPE_STORE	= 0xff,
        _ZMEDIAITEM_TYPE_LIMIT	= ( ZMEDIAITEM_TYPE_STORE + 1 ) 
    } 	ZMEDIAITEM_TYPE;

typedef 
enum _ZMEDIALIST_TYPE
    {
        ZMEDIALIST_TYPE_INVALID	= 0,
        ZMEDIALIST_TYPE_ALL_AUDIO	= 1,
        ZMEDIALIST_TYPE_ALL_ALBUMS	= 2,
        ZMEDIALIST_TYPE_ALL_ARTISTS	= 3,
        ZMEDIALIST_TYPE_ALL_AUDIOGENRES	= 4,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS	= 5,
        ZMEDIALIST_TYPE_ALL_VIDEOS	= 6,
        ZMEDIALIST_TYPE_ALL_PICTURES	= 7,
        ZMEDIALIST_TYPE_ALL_UNKNOWN	= 9,
        ZMEDIALIST_TYPE_ALL_PICTUREALBUMS	= 10,
        ZMEDIALIST_TYPE_ALL_DATERANGES	= 11,
        ZMEDIALIST_TYPE_ALL_USERCARDS	= 12,
        _ZMEDIALIST_TYPE_UNUSED1	= 13,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES	= 14,
        ZMEDIALIST_TYPE_ALL_PODCASTSERIES	= 15,
        ZMEDIALIST_TYPE_ALL_PODCASTAUDIO	= 16,
        _ZMEDIALIST_TYPE_UNUSED2	= 17,
        ZMEDIALIST_TYPE_ALL_INBOXMSGS	= 18,
        ZMEDIALIST_TYPE_ALL_AUDIO_GROUPBYALBUM	= 30,
        ZMEDIALIST_TYPE_ALL_ALBUMARTISTS	= 31,
        ZMEDIALIST_TYPE_ALL_ITEMS_BY_MEDIAID	= 32,
        ZMEDIALIST_TYPE_ALL_ITEMS_BY_FILEPATH	= 33,
        ZMEDIALIST_TYPE_ALBUM_AUDIO	= 40,
        ZMEDIALIST_TYPE_ALBUM_CONTENTS	= 41,
        ZMEDIALIST_TYPE_ARTIST_AUDIO	= 42,
        ZMEDIALIST_TYPE_ARTIST_ALBUMS	= 43,
        ZMEDIALIST_TYPE_ARTIST_CONTENTS	= 44,
        ZMEDIALIST_TYPE_AUDIOGENRE_AUDIO	= 45,
        ZMEDIALIST_TYPE_AUDIOGENRE_ALBUMS	= 46,
        ZMEDIALIST_TYPE_AUDIOGENRE_CONTENTS	= 47,
        ZMEDIALIST_TYPE_PLAYLIST_AUDIO	= 48,
        ZMEDIALIST_TYPE_PLAYLIST_CONTENTS	= 49,
        ZMEDIALIST_TYPE_ARTIST_AUDIO_ALL	= 50,
        ZMEDIALIST_TYPE_ARTIST_AUDIO_ALL_GROUPBYALBUM	= 51,
        ZMEDIALIST_TYPE_ARTIST_AUDIO_ON_STORAGELOCATION	= 52,
        ZMEDIALIST_TYPE_ALBUM_AUDIO_ON_STORAGELOCATION	= 53,
        ZMEDIALIST_TYPE_ARTIST_ALBUMS_ON_STORAGELOCATION	= 54,
        ZMEDIALIST_TYPE_GENRE_AUDIO_ON_STORAGELOCATION	= 55,
        ZMEDIALIST_TYPE_DATERANGE_PICTURES	= 60,
        ZMEDIALIST_TYPE_DATERANGE_CONTENTS	= 61,
        ZMEDIALIST_TYPE_PICTUREALBUM_PICTURES	= 62,
        ZMEDIALIST_TYPE_PICTUREALBUM_PICTUREALBUMS	= 63,
        ZMEDIALIST_TYPE_PICTUREALBUM_CONTENTS	= 64,
        ZMEDIALIST_TYPE_FOLDER_AUDIO	= 70,
        ZMEDIALIST_TYPE_FOLDER_VIDEOS	= 71,
        ZMEDIALIST_TYPE_FOLDER_PICTURES	= 72,
        ZMEDIALIST_TYPE_FOLDER_FOLDERS	= 73,
        ZMEDIALIST_TYPE_FOLDER_UNKNOWNS	= 74,
        ZMEDIALIST_TYPE_FOLDER_ALBUMS	= 75,
        ZMEDIALIST_TYPE_FOLDER_PLAYLISTS	= 76,
        ZMEDIALIST_TYPE_FOLDER_PODCASTAUDIO	= 77,
        ZMEDIALIST_TYPE_FOLDER_PODCASTSERIES	= 78,
        ZMEDIALIST_TYPE_FOLDER_AUDIOBOOKPARTS	= 81,
        ZMEDIALIST_TYPE_FOLDER_GAMES	= 82,
        ZMEDIALIST_TYPE_FOLDER_ARTISTS	= 83,
        ZMEDIALIST_TYPE_FOLDER_PICTURECONTENTS_ON_STORAGELOCATION	= 84,
        ZMEDIALIST_TYPE_FOLDER_FOLDERS_ON_STORAGELOCATION	= 85,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_OTHER	= 90,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_MOVIE	= 91,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_TVSHOW	= 92,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_MUSICVIDEO	= 93,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_PODCAST	= 94,
        ZMEDIALIST_TYPE_ALL_VIDEOSERIES_PERSONAL	= 95,
        ZMEDIALIST_TYPE_VIDEOSERIES_VIDEOS	= 100,
        ZMEDIALIST_TYPE_VIDEOSERIES_CONTENTS	= 101,
        ZMEDIALIST_TYPE_ALL_VIDEOS_OTHER	= 110,
        ZMEDIALIST_TYPE_ALL_VIDEOS_MOVIE	= 111,
        ZMEDIALIST_TYPE_ALL_VIDEOS_TVSHOW	= 112,
        ZMEDIALIST_TYPE_ALL_VIDEOS_MUSICVIDEO	= 113,
        ZMEDIALIST_TYPE_ALL_VIDEOS_PODCAST	= 114,
        ZMEDIALIST_TYPE_ALL_VIDEOS_PERSONAL	= 115,
        ZMEDIALIST_TYPE_ALL_VIDEOS_NONUGC	= 116,
        ZMEDIALIST_TYPE_ALL_PODCASTSERIES_AUDIO	= 120,
        ZMEDIALIST_TYPE_ALL_PODCASTSERIES_VIDEO	= 121,
        ZMEDIALIST_TYPE_PODCASTSERIES_CONTENTS	= 122,
        ZMEDIALIST_TYPE_PODCASTSERIES_VIDEO	= 123,
        ZMEDIALIST_TYPE_PODCASTSERIES_AUDIOPODCASTS	= 124,
        ZMEDIALIST_TYPE_PODCASTSERIES_CONTENTS_LOCAL	= 125,
        ZMEDIALIST_TYPE_PODCASTSERIES_CONTENTS_LOCAL_AUDIO	= 126,
        ZMEDIALIST_TYPE_PODCASTSERIES_CONTENTS_LOCAL_VIDEO	= 127,
        ZMEDIALIST_TYPE_ALL_PODCASTEPISODES_BY_URL	= 128,
        ZMEDIALIST_TYPE_OTHER	= 130,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT	= 150,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT_AUDIO	= 151,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT_ALBUMS	= 152,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT_ARTISTS	= 153,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT_PLAYLISTS	= 154,
        ZMEDIALIST_TYPE_ALL_CLOUDCONTENT_AUDIOGENRE	= 155,
        ZMEDIALIST_TYPE_ALL_USERCARDS_FRIENDS	= 160,
        ZMEDIALIST_TYPE_UNFILTERED_ALBUM_CONTENTS	= 170,
        ZMEDIALIST_TYPE_UNFILTERED_ARTIST_CONTENTS	= 171,
        ZMEDIALIST_TYPE_UNFILTERED_AUDIOGENRE_CONTENTS	= 172,
        ZMEDIALIST_TYPE_UNFILTERED_ARTIST_AUDIO	= 173,
        ZMEDIALIST_TYPE_UNFILTERED_FOLDER_CONTENTS	= 174,
        ZMEDIALIST_TYPE_ALL_AUDIOBOOKS	= 180,
        ZMEDIALIST_TYPE_ALL_AUDIOBOOKPARTS	= 181,
        ZMEDIALIST_TYPE_AUDIOBOOK_AUDIOBOOKSPARTS	= 182,
        ZMEDIALIST_TYPE_ALL_GAMES	= 190,
        ZMEDIALIST_TYPE_ALL_GAMERUNTIMES	= 191,
        ZMEDIALIST_TYPE_ALL_GAMESTORAGES	= 192,
        ZMEDIALIST_TYPE_ALL_GAMES_CREATOR	= 193,
        ZMEDIALIST_TYPE_ALL_GAMES_COMMUNITY	= 194,
        ZMEDIALIST_TYPE_ALL_GAMES_APPLICATIONS	= 195,
        ZMEDIALIST_TYPE_ALL_CLOUDTASKS	= 200,
        ZMEDIALIST_TYPE_ALL_CLOUDJOBS	= 201,
        ZMEDIALIST_TYPE_CLOUDJOB_CLOUDITEMS	= 202,
        ZMEDIALIST_TYPE_ALL_CARTITEMS	= 210,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS_STATIC	= 220,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS_USERCARD	= 221,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS_CHANNEL	= 222,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS_STATIC_NO_QUICKLIST	= 223,
        ZMEDIALIST_TYPE_ALL_PLAYLISTS_PICTURETAG	= 224,
        ZMEDIALIST_TYPE_ALL_QUICKLAUNCH	= 230,
        ZMEDIALIST_TYPE_QUICKLAUNCH_FAVORITES	= 231,
        ZMEDIALIST_TYPE_QUICKLAUNCH_RECENT	= 232,
        ZMEDIALIST_TYPE_QUICKLAUNCH_NEW	= 233,
        ZMEDIALIST_TYPE_ALL_BOOKMARKS	= 240,
        ZMEDIALIST_TYPE_ALL_LETTERS	= 250,
        ZMEDIALIST_TYPE_SPECIAL_ALLCHANNELCONTENT	= 260,
        ZMEDIALIST_TYPE_SPECIAL_ALLMUSIC	= 261,
        ZMEDIALIST_TYPE_ALL_TRANSIENTAUDIO	= 280,
        ZMEDIALIST_TYPE_ALL_TRANSIENTPICTURES	= 281,
        ZMEDIALIST_TYPE_ALL_RADIOPRESETS	= 290,
        ZMEDIALIST_TYPE_PLAYLIST_PICTURETAG	= 300,
        ZMEDIALIST_TYPE_PLAYLIST_PICTUREALBUM	= 302,
        ZMEDIALIST_TYPE_FOLDER_ROOT_PICTURE_FOLDERS	= 303,
        ZMEDIALIST_TYPE_FOLDER_PICTURECONTENTS	= 304,
        ZMEDIALIST_TYPE_FAVORITE_PICTURES	= 305,
        ZMEDIALIST_TYPE_ALL_PICTURECONTENTS	= 306,
        ZMEDIALIST_TYPE_ALL_ITEMS_BY_PERSISTENT_UNIQUEID	= 307,
        ZMEDIALIST_TYPE_FOLDER_PICTUREALBUMS	= 308,
        ZMEDIALIST_TYPE_ALL_EVENTS	= 350,
        ZMEDIALIST_TYPE_PICTUREALBUM_EVENTS	= 351,
        ZMEDIALIST_TYPE_EVENTCONTENTS	= 352,
        ZMEDIALIST_TYPE_ALL_PODCASTAUDIO_ASAUDIO	= 400,
        ZMEDIALIST_TYPE_PODCASTSERIES_AUDIOPODCASTS_ASCENDINGDATE	= 401,
        ZMEDIALIST_TYPE_PODCASTSERIES_AUDIOPODCASTS_ASCENDINGDATE_ASAUDIO	= 402,
        ZMEDIALIST_TYPE_PODCASTSERIES_AUDIOPODCASTS_DESCENDINGDATE	= 403,
        ZMEDIALIST_TYPE_PODCASTSERIES_AUDIOPODCASTS_DESCENDINGDATE_ASAUDIO	= 404,
        ZMEDIALIST_TYPE_PODCASTSERIES_CONTENTS_LOCAL_AUDIO_ASAUDIO	= 405,
        ZMEDIALIST_TYPE_ALL_AUDIO_BY_ADDED_DATE	= 412,
        ZMEDIALIST_TYPE_ALL_AUDIO_BY_PLAYCOUNT	= 413,
        ZMEDIALIST_TYPE_ALL_AUDIO_BY_PLAYEDTIME	= 414,
        ZMEDIALIST_TYPE_ALL_AUDIO_BY_FAVORITE_DATE	= 415,
        ZMEDIALIST_TYPE_TAGGED_PICTURES	= 416,
        ZMEDIALIST_TYPE_ALL_PICTUREALBUM_BY_REMOTEID	= 417,
        ZMEDIALIST_TYPE_ALL_MUSICAUDIOS_UNSORTED	= 418,
        ZMEDIALIST_TYPE_ALL_POCASTAUDIOS_UNSORTED	= 419,
        ZMEDIALIST_TYPE_ALL_ARTISTS_UNSORTED	= 420,
        ZMEDIALIST_TYPE_ALL_ALBUMS_UNSORTED	= 421,
        ZMEDIALIST_TYPE_FAVORITE_PICTURECONTENTS	= 422,
        ZMEDIALIST_TYPE_ALL_PICTUREVIDEO_BY_REMOTEID	= 423,
        _ZMEDIALIST_TYPE_LIMIT	= ( ZMEDIALIST_TYPE_ALL_PICTUREVIDEO_BY_REMOTEID + 1 ) 
    } 	ZMEDIALIST_TYPE;

typedef 
enum _ZMEDIALIB_NOTIFICATIONTYPE
    {
        ZMEDIALIB_NOTIFICATIONTYPE_INVALID	= 0,
        ZMEDIALIB_NOTIFICATIONTYPE_SMARTDJSTATUSCHANGED	= ( ZMEDIALIB_NOTIFICATIONTYPE_INVALID + 1 ) ,
        ZMEDIALIB_NOTIFICATIONTYPE_COPYPROGRESS	= ( ZMEDIALIB_NOTIFICATIONTYPE_SMARTDJSTATUSCHANGED + 1 ) ,
        ZMEDIALIB_NOTIFICATIONTYPE_COPYCOMPLETE	= ( ZMEDIALIB_NOTIFICATIONTYPE_COPYPROGRESS + 1 ) ,
        _ZMEDIALIB_NOTIFICATIONTYPE_COUNT	= ( ZMEDIALIB_NOTIFICATIONTYPE_COPYCOMPLETE + 1 ) 
    } 	ZMEDIALIB_NOTIFICATIONTYPE;

typedef struct _ZMEDIALIB_NOTIFICATION_COPYPROGRESS
    {
    LONGLONG llCurrentBytes;
    LONGLONG llTotalBytes;
    } 	ZMEDIALIB_NOTIFICATION_COPYPROGRESS;

// Disable /W4 compiler warning C4201: nameless struct/union
#pragma warning(push)
#pragma warning(disable:4201)  // Disable C4201: nameless struct/union
typedef struct _ZMEDIALIB_NOTIFICATION
    {
    ZMEDIALIB_NOTIFICATIONTYPE eType;
    /* [switch_is][switch_type] */ union 
        {
        /* [case()] */ ZMEDIALIB_NOTIFICATION_COPYPROGRESS CopyProgress;
        /* [case()] */ HRESULT hr;
        /* [default] */  /* Empty union arm */ 
        } 	;
    } 	ZMEDIALIB_NOTIFICATION;

#pragma warning(pop)
typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_ATTRIBUTE_TYPE
    {
        ZMEDIAITEM_ATTRIBUTE_TYPE_INVALID	= 0,
        ZMEDIAITEM_ATTRIBUTE_TYPE_INT	= 0x10000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_STRING	= 0x20000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_DATETIME	= 0x30000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_GUID	= 0x40000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_BLOB	= 0x50000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_UINT	= 0x60000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_USHORT	= 0x70000,
        ZMEDIAITEM_ATTRIBUTE_TYPE_RELATION	= 0x100000,
        ZMEDAIITEM_ATTRIBUTE_TYPE_MASK	= 0xff0000
    } 	ZMEDIAITEM_ATTRIBUTE_TYPE;

typedef UINT ZMEDIAITEM_ATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_INTATTRIBUTE
    {
        ZMEDIAITEM_INTATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_INT,
        ZMEDIAITEM_ATTRIBUTE_TRACKNUMBER	= ( ZMEDIAITEM_INTATTRIBUTE_INVALID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_RATING	= ( ZMEDIAITEM_ATTRIBUTE_TRACKNUMBER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DURATION	= ( ZMEDIAITEM_ATTRIBUTE_RATING + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FORMATCODE	= ( ZMEDIAITEM_ATTRIBUTE_DURATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_FORMATCODE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYWINDOW	= ( ZMEDIAITEM_ATTRIBUTE_PLAYCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_WIDTH	= ( ZMEDIAITEM_ATTRIBUTE_PLAYWINDOW + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_HEIGHT	= ( ZMEDIAITEM_ATTRIBUTE_WIDTH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_METAGENRE	= ( ZMEDIAITEM_ATTRIBUTE_HEIGHT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FILESIZE	= ( ZMEDIAITEM_ATTRIBUTE_METAGENRE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DISKNUMBER	= ( ZMEDIAITEM_ATTRIBUTE_FILESIZE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_AUDIOTYPE	= ( ZMEDIAITEM_ATTRIBUTE_DISKNUMBER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VIDEOTYPE	= ( ZMEDIAITEM_ATTRIBUTE_AUDIOTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_APPID	= ( ZMEDIAITEM_ATTRIBUTE_VIDEOTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_BOOKMARK	= ( ZMEDIAITEM_ATTRIBUTE_APPID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FLAGS	= ( ZMEDIAITEM_ATTRIBUTE_BOOKMARK + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ISSUBSCRIBED	= ( ZMEDIAITEM_ATTRIBUTE_FLAGS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SORTORDER	= ( ZMEDIAITEM_ATTRIBUTE_ISSUBSCRIBED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EPISODENUMBER	= ( ZMEDIAITEM_ATTRIBUTE_SORTORDER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SEASONNUMBER	= ( ZMEDIAITEM_ATTRIBUTE_EPISODENUMBER + 1 ) ,
        _ZMEDIAITEM_ATTRIBUTE_ENCOUNTERREAD	= ( ZMEDIAITEM_ATTRIBUTE_SEASONNUMBER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_USERCARD_PLAYLIST_TYPE	= ( _ZMEDIAITEM_ATTRIBUTE_ENCOUNTERREAD + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_USERCARDFLAGS	= ( ZMEDIAITEM_ATTRIBUTE_USERCARD_PLAYLIST_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIAPROPERTIES	= ( ZMEDIAITEM_ATTRIBUTE_USERCARDFLAGS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUDCONTENT_REFCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAPROPERTIES + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_FLAGS	= ( ZMEDIAITEM_ATTRIBUTE_CLOUDCONTENT_REFCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_STATE	= ( ZMEDIAITEM_ATTRIBUTE_CS_FLAGS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_CS_STATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_REFCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_CS_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_POSITION	= ( ZMEDIAITEM_ATTRIBUTE_CS_REFCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_PRIORITY	= ( ZMEDIAITEM_ATTRIBUTE_CS_POSITION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_EXECUTERESULT	= ( ZMEDIAITEM_ATTRIBUTE_CS_PRIORITY + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTMESSAGEID	= ( ZMEDIAITEM_ATTRIBUTE_CS_EXECUTERESULT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTITEMTYPE	= ( ZMEDIAITEM_ATTRIBUTE_CARTMESSAGEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYLIST_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_CARTITEMTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ISEXPLICIT	= ( ZMEDIAITEM_ATTRIBUTE_PLAYLIST_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CHANNEL_STATUS	= ( ZMEDIAITEM_ATTRIBUTE_ISEXPLICIT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUD_ERROR	= ( ZMEDIAITEM_ATTRIBUTE_CHANNEL_STATUS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_AUTHENTICATION_REQUIRED	= ( ZMEDIAITEM_ATTRIBUTE_CLOUD_ERROR + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PERSISTEDCLOUDOBJ_PHASE1	= ( ZMEDIAITEM_ATTRIBUTE_AUTHENTICATION_REQUIRED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PERSISTEDCLOUDOBJ_PHASE2	= ( ZMEDIAITEM_ATTRIBUTE_PERSISTEDCLOUDOBJ_PHASE1 + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUD_PLAYCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_PERSISTEDCLOUDOBJ_PHASE2 + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUD_SKIPCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_CLOUD_PLAYCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_GAME_FLAGS	= ( ZMEDIAITEM_ATTRIBUTE_CLOUD_SKIPCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_LIST	= ( ZMEDIAITEM_ATTRIBUTE_GAME_FLAGS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMTYPE	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_LIST + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMORDER	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMDATA	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMORDER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_INBOXMSG_MSGID	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMDATA + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_INBOXMSG_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_INBOXMSG_MSGID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLIPTYPE	= ( ZMEDIAITEM_ATTRIBUTE_INBOXMSG_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CS_PERSISTHANDLEVALUE	= ( ZMEDIAITEM_ATTRIBUTE_CLIPTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUD_PLAYTIME	= ( ZMEDIAITEM_ATTRIBUTE_CS_PERSISTHANDLEVALUE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTISTVIEW_FILLERFILE_PRESENT	= ( ZMEDIAITEM_ATTRIBUTE_CLOUD_PLAYTIME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LICENSE_STATE	= ( ZMEDIAITEM_ATTRIBUTE_ARTISTVIEW_FILLERFILE_PRESENT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EXPERIMENT_ID	= ( ZMEDIAITEM_ATTRIBUTE_LICENSE_STATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MAX_LOCAL_SERIES_ITEMS	= ( ZMEDIAITEM_ATTRIBUTE_EXPERIMENT_ID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SERIES_REFRESH_INTERVAL	= ( ZMEDIAITEM_ATTRIBUTE_MAX_LOCAL_SERIES_ITEMS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DOWNLOAD_STATE	= ( ZMEDIAITEM_ATTRIBUTE_SERIES_REFRESH_INTERVAL + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DOWNLOAD_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_DOWNLOAD_STATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCAST_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_DOWNLOAD_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SUBSCRIPTION_STATE	= ( ZMEDIAITEM_ATTRIBUTE_PODCAST_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_ACQUIRED_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_SUBSCRIPTION_STATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCAST_DOWNLOAD_PROGRESS	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_ACQUIRED_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_LATITUDE	= ( ZMEDIAITEM_ATTRIBUTE_PODCAST_DOWNLOAD_PROGRESS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_LONGITUDE	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_LATITUDE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYLIST_PICTUREALBUM	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_LONGITUDE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FM_FREQUENCY	= ( ZMEDIAITEM_ATTRIBUTE_PLAYLIST_PICTUREALBUM + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_RADIO_REGION	= ( ZMEDIAITEM_ATTRIBUTE_FM_FREQUENCY + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_ACTUALTYPE	= ( ZMEDIAITEM_ATTRIBUTE_RADIO_REGION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SRCPATHHASH_FORMEDIAGROVELER	= ( ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_ACTUALTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_HEADING	= ( ZMEDIAITEM_ATTRIBUTE_SRCPATHHASH_FORMEDIAGROVELER + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_ALTITUDE	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_HEADING + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_ORIENTATION	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_ALTITUDE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PICTURE_RATING	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_ORIENTATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_NUM_ATTEMPTS	= ( ZMEDIAITEM_ATTRIBUTE_PICTURE_RATING + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_LAST_ERROR	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_NUM_ATTEMPTS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_DOWNLOAD_PROGRESS	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_LAST_ERROR + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ITEM_LASTERROR	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_DOWNLOAD_PROGRESS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_ITEM_LASTERROR + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_EXTENDED_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_COMPLETE	= ( ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_EXTENDED_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_CONTEXT	= ( ZMEDIAITEM_ATTRIBUTE_DORADO_PLAYLIST_COMPLETE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_STREAMSTATUS	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_CONTEXT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PROHIBIT_LOW_POWER_MODE	= ( ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_STREAMSTATUS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIACONTROLS	= ( ZMEDIAITEM_ATTRIBUTE_PROHIBIT_LOW_POWER_MODE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SMARTDJ_SCHEMEID	= ( ZMEDIAITEM_ATTRIBUTE_MEDIACONTROLS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMZMEDIATYPE	= ( ZMEDIAITEM_ATTRIBUTE_SMARTDJ_SCHEMEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCAST_DOWNLOAD_FAIL_COUNT	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEMZMEDIATYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_ISSTREAMING	= ( ZMEDIAITEM_ATTRIBUTE_PODCAST_DOWNLOAD_FAIL_COUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VECTOR_DOWNLOAD_STATE	= ( ZMEDIAITEM_ATTRIBUTE_TRANSIENTITEM_ISSTREAMING + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PROCESS_ID	= ( ZMEDIAITEM_ATTRIBUTE_VECTOR_DOWNLOAD_STATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_COVERIMAGE	= ( ZMEDIAITEM_ATTRIBUTE_PROCESS_ID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_COVERIMAGE_SELECT_LAST_ITEM	= ( ZMEDIAITEM_ATTRIBUTE_COVERIMAGE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_COVERIMAGE_NOT_PRESENT	= ( ZMEDIAITEM_ATTRIBUTE_COVERIMAGE_SELECT_LAST_ITEM + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_STORAGELOCATION	= ( ZMEDIAITEM_ATTRIBUTE_COVERIMAGE_NOT_PRESENT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LICENSE_FAIL_COUNT	= ( ZMEDIAITEM_ATTRIBUTE_STORAGELOCATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_OTA_MDLC_FAIL_COUNT	= ( ZMEDIAITEM_ATTRIBUTE_LICENSE_FAIL_COUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PICTURE_RATING_PERCENT	= ( ZMEDIAITEM_ATTRIBUTE_OTA_MDLC_FAIL_COUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SAMPLERATE	= ( ZMEDIAITEM_ATTRIBUTE_PICTURE_RATING_PERCENT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_NUMCHANNELS	= ( ZMEDIAITEM_ATTRIBUTE_SAMPLERATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_AUDIOWAVECODEC	= ( ZMEDIAITEM_ATTRIBUTE_NUMCHANNELS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_AUDIOBITRATE	= ( ZMEDIAITEM_ATTRIBUTE_AUDIOWAVECODEC + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SCANTYPE	= ( ZMEDIAITEM_ATTRIBUTE_AUDIOBITRATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VIDEOFOURCCCODEC	= ( ZMEDIAITEM_ATTRIBUTE_SCANTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VIDEOBITRATE	= ( ZMEDIAITEM_ATTRIBUTE_VIDEOFOURCCCODEC + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FRAMESPERMILLISECOND	= ( ZMEDIAITEM_ATTRIBUTE_VIDEOBITRATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ENABLE_LOW_LATENCY	= ( ZMEDIAITEM_ATTRIBUTE_FRAMESPERMILLISECOND + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EVENT_ISCHANGED	= ( ZMEDIAITEM_ATTRIBUTE_ENABLE_LOW_LATENCY + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EVENT_ISLOOSE	= ( ZMEDIAITEM_ATTRIBUTE_EVENT_ISCHANGED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EVENT_ITEMCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_EVENT_ISLOOSE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FLAG_DRMPROTECTED	= ( ZMEDIAITEM_ATTRIBUTE_EVENT_ITEMCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_GENRE_AUDIOCOUNT	= ( ZMEDIAITEM_ATTRIBUTE_FLAG_DRMPROTECTED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIAOM_STORAGELOCATION	= ( ZMEDIAITEM_ATTRIBUTE_GENRE_AUDIOCOUNT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIAOM_MUSICALBUMSTORAGELOCATION	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAOM_STORAGELOCATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIAOM_AUDIOSTORAGELOCATION	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAOM_MUSICALBUMSTORAGELOCATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIAOM_VIDEOSTORAGELOCATION	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAOM_AUDIOSTORAGELOCATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PICTUREALBUM_AUTHENTICATION_DEPRECATED	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAOM_VIDEOSTORAGELOCATION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PICTUREALBUMTYPE	= ( ZMEDIAITEM_ATTRIBUTE_PICTUREALBUM_AUTHENTICATION_DEPRECATED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_INCOLLECTION	= ( ZMEDIAITEM_ATTRIBUTE_PICTUREALBUMTYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ISDISABLED	= ( ZMEDIAITEM_ATTRIBUTE_INCOLLECTION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LEGACYID	= ( ZMEDIAITEM_ATTRIBUTE_ISDISABLED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_MEDIA_RIGHTS	= ( ZMEDIAITEM_ATTRIBUTE_LEGACYID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYLIST_AUTODOWNLOAD	= ( ZMEDIAITEM_ATTRIBUTE_MEDIA_RIGHTS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_WIFI_ONLY	= ( ZMEDIAITEM_ATTRIBUTE_PLAYLIST_AUTODOWNLOAD + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCAST_NEW_COUNT	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_WIFI_ONLY + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ISACQUIREDITEM	= ( ZMEDIAITEM_ATTRIBUTE_PODCAST_NEW_COUNT + 1 ) ,
        _ZMEDIAITEM_INTATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_ISACQUIREDITEM + 1 ) 
    } 	ZMEDIAITEM_INTATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_USHORTATTRIBUTE
    {
        ZMEDIAITEM_USHORTATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_USHORT,
        ZMEDIAITEM_ATTRIBUTE_SORTGROUPID	= ( ZMEDIAITEM_USHORTATTRIBUTE_INVALID + 1 ) ,
        _ZMEDIAITEM_USHORTATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_SORTGROUPID + 1 ) 
    } 	ZMEDIAITEM_USHORTATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_UINTATTRIBUTE
    {
        ZMEDIAITEM_UINTATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_UINT,
        ZMEDIAITEM_ATTRIBUTE_TAGS	= ( ZMEDIAITEM_UINTATTRIBUTE_INVALID + 1 ) ,
        _ZMEDIAITEM_UINTATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_TAGS + 1 ) 
    } 	ZMEDIAITEM_UINTATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_GUIDATTRIBUTE
    {
        ZMEDIAITEM_GUIDATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_GUID,
        ZMEDIAITEM_ATTRIBUTE_MEDIAID	= ( ZMEDIAITEM_GUIDATTRIBUTE_INVALID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VIRTUALAPPID	= ( ZMEDIAITEM_ATTRIBUTE_MEDIAID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PARENT_MEDIAID	= ( ZMEDIAITEM_ATTRIBUTE_VIRTUALAPPID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ALBUM_MEDIAID	= ( ZMEDIAITEM_ATTRIBUTE_PARENT_MEDIAID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PERSISTENT_UNIQUEID	= ( ZMEDIAITEM_ATTRIBUTE_ALBUM_MEDIAID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PRODUCTID	= ( ZMEDIAITEM_ATTRIBUTE_PERSISTENT_UNIQUEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PLAYLIST_ENTRYID	= ( ZMEDIAITEM_ATTRIBUTE_PRODUCTID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ACTIONABLEID	= ( ZMEDIAITEM_ATTRIBUTE_PLAYLIST_ENTRYID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CONTENTFILESTOREGUID	= ( ZMEDIAITEM_ATTRIBUTE_ACTIONABLEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FOLDERSTOREGUID	= ( ZMEDIAITEM_ATTRIBUTE_CONTENTFILESTOREGUID + 1 ) ,
        _ZMEDIAITEM_GUIDATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_FOLDERSTOREGUID + 1 ) 
    } 	ZMEDIAITEM_GUIDATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_STRINGATTRIBUTE
    {
        ZMEDIAITEM_STRINGATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_STRING,
        ZMEDIAITEM_ATTRIBUTE_NAME	= ( ZMEDIAITEM_STRINGATTRIBUTE_INVALID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTIST	= ( ZMEDIAITEM_ATTRIBUTE_NAME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ALBUM	= ( ZMEDIAITEM_ATTRIBUTE_ARTIST + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_GENRE	= ( ZMEDIAITEM_ATTRIBUTE_ALBUM + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PARENTALRATING	= ( ZMEDIAITEM_ATTRIBUTE_GENRE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_DESCRIPTION	= ( ZMEDIAITEM_ATTRIBUTE_PARENTALRATING + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_GUIDETEXT	= ( ZMEDIAITEM_ATTRIBUTE_DESCRIPTION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VIDEOSERIES	= ( ZMEDIAITEM_ATTRIBUTE_GUIDETEXT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCASTSERIES	= ( ZMEDIAITEM_ATTRIBUTE_VIDEOSERIES + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FILEPATH	= ( ZMEDIAITEM_ATTRIBUTE_PODCASTSERIES + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTPATH	= ( ZMEDIAITEM_ATTRIBUTE_FILEPATH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FILENAME	= ( ZMEDIAITEM_ATTRIBUTE_ARTPATH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_URL	= ( ZMEDIAITEM_ATTRIBUTE_FILENAME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SOURCE	= ( ZMEDIAITEM_ATTRIBUTE_URL + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_USERSTATUS	= ( ZMEDIAITEM_ATTRIBUTE_SOURCE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ZUNETAG	= ( ZMEDIAITEM_ATTRIBUTE_USERSTATUS + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_USERGUID	= ( ZMEDIAITEM_ATTRIBUTE_ZUNETAG + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_BACKGROUND_PATH	= ( ZMEDIAITEM_ATTRIBUTE_USERGUID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_USERFRIENDLYNAME	= ( ZMEDIAITEM_ATTRIBUTE_BACKGROUND_PATH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTURL	= ( ZMEDIAITEM_ATTRIBUTE_USERFRIENDLYNAME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_INBOXMSG_CONTENT	= ( ZMEDIAITEM_ATTRIBUTE_ARTURL + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_VERSION	= ( ZMEDIAITEM_ATTRIBUTE_INBOXMSG_CONTENT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_KID	= ( ZMEDIAITEM_ATTRIBUTE_VERSION + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_COPYRIGHT	= ( ZMEDIAITEM_ATTRIBUTE_KID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_REQUIREDFIRMWARE	= ( ZMEDIAITEM_ATTRIBUTE_COPYRIGHT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_NAME_RAW	= ( ZMEDIAITEM_ATTRIBUTE_REQUIREDFIRMWARE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_OFFER_ID	= ( ZMEDIAITEM_ATTRIBUTE_NAME_RAW + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CARTENTRY_ITEM_NAME	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_OFFER_ID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTPATH_SMALL	= ( ZMEDIAITEM_ATTRIBUTE_CARTENTRY_ITEM_NAME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_TEXT	= ( ZMEDIAITEM_ATTRIBUTE_ARTPATH_SMALL + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_DISPLAYART	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_TEXT + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_TRANSIENT_CLIENT_SID	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_DISPLAYART + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_YOMI_NAME	= ( ZMEDIAITEM_ATTRIBUTE_TRANSIENT_CLIENT_SID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_MARKETPLACEID	= ( ZMEDIAITEM_ATTRIBUTE_YOMI_NAME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_MARKETPLACESERIESID	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_MARKETPLACEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FOLDER_COVER_FILEPATH	= ( ZMEDIAITEM_ATTRIBUTE_QUICKLAUNCH_ITEM_MARKETPLACESERIESID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_APP_DSTOKENID	= ( ZMEDIAITEM_ATTRIBUTE_FOLDER_COVER_FILEPATH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_INSTANCE_ID	= ( ZMEDIAITEM_ATTRIBUTE_APP_DSTOKENID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_LICENSE_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_INSTANCE_ID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_ENCODING_TYPE	= ( ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_LICENSE_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_STREAMING_INSTANCE_ID	= ( ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_DOWNLOAD_ENCODING_TYPE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ENCODINGPROFILE	= ( ZMEDIAITEM_ATTRIBUTE_CLOUDSYNC_STREAMING_INSTANCE_ID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FOLDERPATH	= ( ZMEDIAITEM_ATTRIBUTE_ENCODINGPROFILE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTURL_SMALL	= ( ZMEDIAITEM_ATTRIBUTE_FOLDERPATH + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_REMOTEID	= ( ZMEDIAITEM_ATTRIBUTE_ARTURL_SMALL + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FILEPATH_NOGENERATE	= ( ZMEDIAITEM_ATTRIBUTE_REMOTEID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PICTUREALBUM_REVISIONSTAMP	= ( ZMEDIAITEM_ATTRIBUTE_FILEPATH_NOGENERATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FILENAME_NOGENERATE	= ( ZMEDIAITEM_ATTRIBUTE_PICTUREALBUM_REVISIONSTAMP + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_PODCAST_HOME_PAGE_URL	= ( ZMEDIAITEM_ATTRIBUTE_FILENAME_NOGENERATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ARTPATH_READ	= ( ZMEDIAITEM_ATTRIBUTE_PODCAST_HOME_PAGE_URL + 1 ) ,
        _ZMEDIAITEM_STRINGATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_ARTPATH_READ + 1 ) 
    } 	ZMEDIAITEM_STRINGATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_DATETIMEATTRIBUTE
    {
        ZMEDIAITEM_DATETIMEATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_DATETIME,
        ZMEDIAITEM_ATTRIBUTE_DATE	= ( ZMEDIAITEM_DATETIMEATTRIBUTE_INVALID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FEEDLASTUPDATED	= ( ZMEDIAITEM_ATTRIBUTE_DATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LASTPLAYEDTIME	= ( ZMEDIAITEM_ATTRIBUTE_FEEDLASTUPDATED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LICENSEEXPIREDATE	= ( ZMEDIAITEM_ATTRIBUTE_LASTPLAYEDTIME + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LAST_MODIFIED	= ( ZMEDIAITEM_ATTRIBUTE_LICENSEEXPIREDATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_FAVORITE_DATE	= ( ZMEDIAITEM_ATTRIBUTE_LAST_MODIFIED + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SMARTDJ_NEXT_RETRY_DATE	= ( ZMEDIAITEM_ATTRIBUTE_FAVORITE_DATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_EVENT_STARTDATE	= ( ZMEDIAITEM_ATTRIBUTE_SMARTDJ_NEXT_RETRY_DATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_ADDED_DATE	= ( ZMEDIAITEM_ATTRIBUTE_EVENT_STARTDATE + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_LASTMODIFIED_TIME	= ( ZMEDIAITEM_ATTRIBUTE_ADDED_DATE + 1 ) ,
        _ZMEDIAITEM_DATETIMEATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_LASTMODIFIED_TIME + 1 ) 
    } 	ZMEDIAITEM_DATETIMEATTRIBUTE;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_BLOBATTRIBUTE
    {
        ZMEDIAITEM_BLOBATTRIBUTE_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_BLOB,
        ZMEDIAITEM_ATTRIBUTE_PLAYLIST_RAW_CONTENT	= ( ZMEDIAITEM_BLOBATTRIBUTE_INVALID + 1 ) ,
        ZMEDIAITEM_ATTRIBUTE_SERVER_PLAYLIST_RAW_CONTENT	= ( ZMEDIAITEM_ATTRIBUTE_PLAYLIST_RAW_CONTENT + 1 ) ,
        _ZMEDIAITEM_BLOBATTRIBUTE_LIMIT	= ( ZMEDIAITEM_ATTRIBUTE_SERVER_PLAYLIST_RAW_CONTENT + 1 ) 
    } 	ZMEDIAITEM_BLOBATTRIBUTE;

typedef struct _ZMEDIAITEM_ATTRIBUTEDESC
    {
    ZMEDIAITEM_ATTRIBUTE attrib;
    void *pvVal;
    size_t cbVal;
    HRESULT hr;
    } 	ZMEDIAITEM_ATTRIBUTEDESC;

typedef /* [v1_enum] */ 
enum _ZMEDIAITEM_RELATION
    {
        ZMEDIAITEM_RELATION_INVALID	= ZMEDIAITEM_ATTRIBUTE_TYPE_RELATION,
        ZMEDIAITEM_RELATION_ARTIST	= ( ZMEDIAITEM_RELATION_INVALID + 1 ) ,
        ZMEDIAITEM_RELATION_ALBUM	= ( ZMEDIAITEM_RELATION_ARTIST + 1 ) ,
        ZMEDIAITEM_RELATION_GENRE	= ( ZMEDIAITEM_RELATION_ALBUM + 1 ) ,
        ZMEDIAITEM_RELATION_DATERANGE	= ( ZMEDIAITEM_RELATION_GENRE + 1 ) ,
        ZMEDIAITEM_RELATION_PICTUREALBUM	= ( ZMEDIAITEM_RELATION_DATERANGE + 1 ) ,
        ZMEDIAITEM_RELATION_VIDEOSERIES	= ( ZMEDIAITEM_RELATION_PICTUREALBUM + 1 ) ,
        ZMEDIAITEM_RELATION_PODCASTSERIES	= ( ZMEDIAITEM_RELATION_VIDEOSERIES + 1 ) ,
        ZMEDIAITEM_RELATION_USERCARD	= ( ZMEDIAITEM_RELATION_PODCASTSERIES + 1 ) ,
        ZMEDIAITEM_RELATION_FOLDER	= ( ZMEDIAITEM_RELATION_USERCARD + 1 ) ,
        ZMEDIAITEM_RELATION_COVERIMAGE	= ( ZMEDIAITEM_RELATION_FOLDER + 1 ) ,
        ZMEDIAITEM_RELATION_AUDIOBOOK	= ( ZMEDIAITEM_RELATION_COVERIMAGE + 1 ) ,
        ZMEDIAITEM_RELATION_CLOUDJOB	= ( ZMEDIAITEM_RELATION_AUDIOBOOK + 1 ) ,
        ZMEDIAITEM_RELATION_INBOXMSG_MEDIAITEM	= ( ZMEDIAITEM_RELATION_CLOUDJOB + 1 ) ,
        _ZMEDIAITEM_RELATION_LIMIT	= ( ZMEDIAITEM_RELATION_INBOXMSG_MEDIAITEM + 1 ) 
    } 	ZMEDIAITEM_RELATION;

typedef 
enum _ZMEDIAFOLDER_TYPE
    {
        ZMEDIAFOLDER_TYPE_UNKNOWN	= -1,
        ZMEDIAFOLDER_TYPE_ROOT	= 0,
        ZMEDIAFOLDER_TYPE_PICTURES_ROOT	= 1,
        ZMEDIAFOLDER_TYPE_FAVORITES	= 2,
        ZMEDIAFOLDER_TYPE_CAMERA_ROLL	= 3,
        ZMEDIAFOLDER_TYPE_RECEIVED_PICTURES	= 4,
        ZMEDIAFOLDER_TYPE_SAMPLE_PICTURES	= 5,
        ZMEDIAFOLDER_TYPE_SCREEN_SHOTS	= 6,
        ZMEDIAFOLDER_TYPE_INVALID	= 7,
        ZMEDIAFOLDER_TYPE_COUNT	= 8
    } 	ZMEDIAFOLDER_TYPE;

typedef 
enum _ZMEDIAITEM_THUMBTYPE
    {
        ZMEDIAITEM_THUMBTYPE_INVALID	= -1,
        ZMEDIAITEM_THUMBTYPE_NORMAL	= 0,
        ZMEDIAITEM_THUMBTYPE_TINY	= 1
    } 	ZMEDIAITEM_THUMBTYPE;

typedef 
enum _ZMEDIASPECIALITEM
    {
        ZMEDIASPECIALITEM_INVALID	= 0,
        ZMEDIASPECIALITEM_PLAYLIST_QUICKLIST	= ( ZMEDIASPECIALITEM_INVALID + 1 ) ,
        ZMEDIASPECIALITEM_ALBUM_UNKNOWN	= ( ZMEDIASPECIALITEM_PLAYLIST_QUICKLIST + 1 ) ,
        ZMEDIASPECIALITEM_ARTIST_UNKNOWN	= ( ZMEDIASPECIALITEM_ALBUM_UNKNOWN + 1 ) ,
        ZMEDIASPECIALITEM_AUDIOGENRE_UNKNOWN	= ( ZMEDIASPECIALITEM_ARTIST_UNKNOWN + 1 ) ,
        ZMEDIASPECIALITEM_DATERANGE_UNKNOWN	= ( ZMEDIASPECIALITEM_AUDIOGENRE_UNKNOWN + 1 ) ,
        ZMEDIASPECIALITEM_RADIOPRESETLIST	= ( ZMEDIASPECIALITEM_DATERANGE_UNKNOWN + 1 ) ,
        _ZMEDIASPECIALITEM_COUNT	= ( ZMEDIASPECIALITEM_RADIOPRESETLIST + 1 ) 
    } 	ZMEDIASPECIALITEM;

typedef 
enum _ZMEDIAITEM_VISIBILITY
    {
        ZMEDIAITEM_VISIBILITY_INVALID	= -1,
        ZMEDIAITEM_VISIBILITY_LIBRARY	= 0,
        ZMEDIAITEM_VISIBILITY_HIDDEN	= 1,
        ZMEDIAITEM_VISIBILITY_CLOUD	= 2
    } 	ZMEDIAITEM_VISIBILITY;

typedef 
enum _ZMEDIALIB_WRITELOCK_TYPE
    {
        ZMEDIALIB_WRITELOCK_TYPE_MAJOR_CHANGE	= 0,
        ZMEDIALIB_WRITELOCK_TYPE_MINOR_CHANGE	= ( ZMEDIALIB_WRITELOCK_TYPE_MAJOR_CHANGE + 1 ) 
    } 	ZMEDIALIB_WRITELOCK_TYPE;

typedef 
enum _ZMEDIAITEM_QUICKLAUNCH_LIST
    {
        ZMEDIAITEM_QUICKLAUNCH_LIST_INVALID	= 0,
        ZMEDIAITEM_QUICKLAUNCH_LIST_FAVORITES	= 1,
        ZMEDIAITEM_QUICKLAUNCH_LIST_NEW	= 2,
        ZMEDIAITEM_QUICKLAUNCH_LIST_RECENT	= 3
    } 	ZMEDIAITEM_QUICKLAUNCH_LIST;

typedef 
enum _ZMEDIALIB_DISPOSITION
    {
        ZMEDIALIB_DISPOSITION_OPENEXISTING	= 0,
        ZMEDIALIB_DISPOSITION_OPENALWAYS	= ( ZMEDIALIB_DISPOSITION_OPENEXISTING + 1 ) 
    } 	ZMEDIALIB_DISPOSITION;

typedef 
enum _ZMEDIAITEM_RATING
    {
        ZMEDIAITEM_RATING_UNRATED	= 0,
        ZMEDIAITEM_RATING_DISLIKE_MOST	= 1,
        ZMEDIAITEM_RATING_DISLIKE_MORE	= 2,
        ZMEDIAITEM_RATING_DISLIKE	= 3,
        ZMEDIAITEM_RATING_DISLIKE_SOMEWHAT	= 4,
        ZMEDIAITEM_RATING_DISLIKE_NEUTRAL	= 5,
        ZMEDIAITEM_RATING_LIKE_NEUTRAL	= 6,
        ZMEDIAITEM_RATING_LIKE_SOMEWHAT	= 7,
        ZMEDIAITEM_RATING_LIKE	= 8,
        ZMEDIAITEM_RATING_LIKE_MORE	= 9,
        ZMEDIAITEM_RATING_LIKE_MOST	= 10,
        _ZMEDIAITEM_RATING_COUNT	= ( ZMEDIAITEM_RATING_LIKE_MOST + 1 ) ,
        ZMEDIAITEM_RATING_HATEIT	= 2,
        ZMEDIAITEM_RATING_LOVEIT	= 8,
        _ZMEDIAITEM_RATING_POSITIVE	= ZMEDIAITEM_RATING_LIKE_NEUTRAL
    } 	ZMEDIAITEM_RATING;

typedef 
enum _ZMEDIAITEM_SORTORDER
    {
        ZMEDIAITEM_SORTORDER_NONE	= 0,
        ZMEDIAITEM_SORTORDER_NEWEST_FIRST	= 1,
        ZMEDIAITEM_SORTORDER_OLDEST_FIRST	= 2
    } 	ZMEDIAITEM_SORTORDER;


enum ESubscriptionObjectDownloadState
    {
        eDownloadStateNone	= 0,
        eDownloadStateError	= 1,
        eDownloadStateDownloading	= 2,
        eDownloadStateDownloaded	= 3,
        eDownloadStatePending	= 4
    } ;

enum SUBSCRIPTION_STATE
    {
        SUBSCRIPTION_UNSUBSCRIBED	= 0,
        SUBSCRIPTION_SUBSCRIBED	= 1,
        SUBSCRIPTION_UNSUBSCRIBE_PENDING_DELETE	= 2,
        SUBSCRIPTION_UNSUBSCRIBE_PENDING_NODELETE	= 3
    } ;
typedef 
enum _ZMEDIAITEM_FLAG
    {
        ZMEDIAITEM_FLAG_NONE	= 0,
        ZMEDIAITEM_FLAG_DRMPROTECTED	= 0x1,
        ZMEDIAITEM_FLAG_CONSUMED	= 0x2,
        ZMEDIAITEM_FLAG_ADD_TO_WISHLIST	= 0x4,
        ZMEDIAITEM_FLAG_PREVENT_COPYTOHOST	= 0x8,
        ZMEDIAITEM_FLAG_PREVENT_SEND	= 0x10,
        ZMEDIAITEM_FLAG_RECEIVED_VIASEND	= 0x20,
        ZMEDIAITEM_FLAG_PURCHASE_REQUESTED	= 0x40
    } 	ZMEDIAITEM_FLAG;

typedef 
enum _ZMEDIAITEM_VIDEOTYPE
    {
        ZMEDIAITEM_VIDEOTYPE_INVALID	= 0,
        ZMEDIAITEM_VIDEOTYPE_OTHER	= ( ZMEDIAITEM_VIDEOTYPE_INVALID + 1 ) ,
        ZMEDIAITEM_VIDEOTYPE_MOVIE	= ( ZMEDIAITEM_VIDEOTYPE_OTHER + 1 ) ,
        ZMEDIAITEM_VIDEOTYPE_PODCAST	= ( ZMEDIAITEM_VIDEOTYPE_MOVIE + 1 ) ,
        ZMEDIAITEM_VIDEOTYPE_TVSHOW	= ( ZMEDIAITEM_VIDEOTYPE_PODCAST + 1 ) ,
        ZMEDIAITEM_VIDEOTYPE_MUSICVIDEO	= ( ZMEDIAITEM_VIDEOTYPE_TVSHOW + 1 ) ,
        ZMEDIAITEM_VIDEOTYPE_PERSONAL	= ( ZMEDIAITEM_VIDEOTYPE_MUSICVIDEO + 1 ) ,
        _ZMEDIAITEM_VIDEOTYPE_COUNT	= ( ZMEDIAITEM_VIDEOTYPE_PERSONAL + 1 ) 
    } 	ZMEDIAITEM_VIDEOTYPE;

typedef 
enum _ZMEDIAITEM_PODCASTTYPE
    {
        ZMEDIAITEM_PODCASTTYPE_INVALID	= 0,
        ZMEDIAITEM_PODCASTTYPE_AUDIO	= 1,
        ZMEDIAITEM_PODCASTTYPE_VIDEO	= 2,
        ZMEDIAITEM_PODCASTTYPE_MIXED	= 3
    } 	ZMEDIAITEM_PODCASTTYPE;

typedef 
enum _QUICKLAUNCH_ITEM_CONTEXT_TYPE
    {
        QUICKLAUNCH_ITEM_CONTEXT_TYPE_UNKNOWN	= 0,
        QUICKLAUNCH_ITEM_CONTEXT_TYPE_AUDIO_CONTAINER	= 1,
        QUICKLAUNCH_ITEM_CONTEXT_TYPE_VIDEO_CONTAINER	= 2
    } 	QUICKLAUNCH_ITEM_CONTEXT_TYPE;

typedef 
enum _ZMEDIAITEM_AUDIOTYPE
    {
        ZMEDIAITEM_AUDIOTYPE_INVALID	= 0,
        ZMEDIAITEM_AUDIOTYPE_MUSIC	= ( ZMEDIAITEM_AUDIOTYPE_INVALID + 1 ) ,
        ZMEDIAITEM_AUDIOTYPE_PODCAST	= ( ZMEDIAITEM_AUDIOTYPE_MUSIC + 1 ) ,
        ZMEDIAITEM_AUDIOTYPE_AUDIOBOOK	= ( ZMEDIAITEM_AUDIOTYPE_PODCAST + 1 ) ,
        _ZMEDIAITEM_AUDIOTYPE_COUNT	= ( ZMEDIAITEM_AUDIOTYPE_AUDIOBOOK + 1 ) 
    } 	ZMEDIAITEM_AUDIOTYPE;

typedef 
enum _ZMEDIAITEM_INBOXMSG_TYPE
    {
        ZMEDIAITEM_INBOXMSGTYPE_INVALID	= 0,
        ZMEDIAITEM_INBOXMSGTYPE_TEXT	= ( ZMEDIAITEM_INBOXMSGTYPE_INVALID + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_TRACK	= ( ZMEDIAITEM_INBOXMSGTYPE_TEXT + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_FRIENDREQUEST	= ( ZMEDIAITEM_INBOXMSGTYPE_TRACK + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_ALBUM	= ( ZMEDIAITEM_INBOXMSGTYPE_FRIENDREQUEST + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_PLAYLIST	= ( ZMEDIAITEM_INBOXMSGTYPE_ALBUM + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_PODCAST	= ( ZMEDIAITEM_INBOXMSGTYPE_PLAYLIST + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_PHOTO	= ( ZMEDIAITEM_INBOXMSGTYPE_PODCAST + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_USERCARD	= ( ZMEDIAITEM_INBOXMSGTYPE_PHOTO + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_FORUMMSG	= ( ZMEDIAITEM_INBOXMSGTYPE_USERCARD + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_VIDEO	= ( ZMEDIAITEM_INBOXMSGTYPE_FORUMMSG + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_GAME	= ( ZMEDIAITEM_INBOXMSGTYPE_VIDEO + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_NOTIFICATION	= ( ZMEDIAITEM_INBOXMSGTYPE_GAME + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_MARKETPLACE_PLAYLIST	= ( ZMEDIAITEM_INBOXMSGTYPE_NOTIFICATION + 1 ) ,
        ZMEDIAITEM_INBOXMSGTYPE_UNKNOWN	= ( ZMEDIAITEM_INBOXMSGTYPE_MARKETPLACE_PLAYLIST + 1 ) ,
        _ZMEDIAITEM_INBOXMSGTYPE_COUNT	= ( ZMEDIAITEM_INBOXMSGTYPE_UNKNOWN + 1 ) 
    } 	ZMEDIAITEM_INBOXMSG_TYPE;

typedef 
enum _ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE
    {
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_INVALID	= 0,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_ZMEDIAITEM	= 1,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_RADIO	= 2,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_WEBSITE	= 3,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_THIRD_PARTY	= 4,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_MARKETPLACE_CONTAINER	= 5,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_SMARTDJMIX_LOCAL	= 6,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_SMARTDJMIX_MARKETPLACE	= 7,
        ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE_MARKETPLACE_PODCAST_EPISODE	= 8
    } 	ZMEDIAITEM_QUICKLAUNCH_ITEMTYPE;

typedef 
enum _ZMEDIAITEM_MEDIACONTROLS_FLAGS
    {
        ZMEDIAITEM_MEDIACONTROLS_CANSKIPNEXT	= 0x1,
        ZMEDIAITEM_MEDIACONTROLS_CANSKIPPREVIOUS	= 0x2,
        ZMEDIAITEM_MEDIACONTROLS_CANFASTFORWARD	= 0x4,
        ZMEDIAITEM_MEDIACONTROLS_CANREWIND	= 0x8,
        ZMEDIAITEM_MEDIACONTROLS_CANPAUSE	= 0x10,
        _ZMEDIAITEM_MEDIACONTROLS_ALL	= 0x1f
    } 	ZMEDIAITEM_MEDIACONTROLS_FLAGS;

typedef 
enum _ZMEDIAITEM_VECTOR_DOWNLOAD_STATE
    {
        ZMEDIAITEM_VECTOR_DOWNLOAD_STATE_INVALID_OR_PENDING	= 0,
        ZMEDIAITEM_VECTOR_DOWNLOAD_STATE_ATTEMPTED	= ( ZMEDIAITEM_VECTOR_DOWNLOAD_STATE_INVALID_OR_PENDING + 1 ) 
    } 	ZMEDIAITEM_VECTOR_DOWNLOAD_STATE;

#define ZMEDIAITEM_MAKE_SPECIALITEM(type, value) (ZMEDIAITEM)(DWORD)(((type) << 24) | ((value) & 0xffffff))
#define	ZMEDIAITEM_ROOTFOLDER	( ( ZMEDIAITEM  )( DWORD  )(( ( ZMEDIAITEM_TYPE_FOLDER << 24 )  | ( 0xffffffff & 0xffffff )  ) ) )

#define	ZMEDIAITEM_ROOTPICTUREALBUM	( ( ZMEDIAITEM  )( DWORD  )(( ( ZMEDIAITEM_TYPE_PICTUREALBUM << 24 )  | ( 0xffffffff & 0xffffff )  ) ) )

#define	ZMEDIAITEM_FMRADIO	( ( ZMEDIAITEM  )( DWORD  )(( ( ZMEDIAITEM_TYPE_UNKNOWN << 24 )  | ( 0xffffffff & 0xffffff )  ) ) )

#define	ZMEDIAITEM_LETTER_PERIOD	( ( ZMEDIAITEM  )( DWORD  )(( ( ZMEDIAITEM_TYPE_LETTER << 24 )  | ( 0xfffffffe & 0xffffff )  ) ) )

#define	ZMEDIAITEM_LETTER_MISCELLANEOUS	( ( ZMEDIAITEM  )( DWORD  )(( ( ZMEDIAITEM_TYPE_LETTER << 24 )  | ( 0xffffffff & 0xffffff )  ) ) )

typedef 
enum _ZMEDIAITEM_USERCARDFLAG
    {
        ZMEDIAITEM_USERCARDFLAG_BLOCKED	= 0x1,
        ZMEDIAITEM_USERCARDFLAG_FRIEND	= 0x2,
        ZMEDIAITEM_USERCARDFLAG_ME	= 0x10,
        ZMEDIAITEM_USERCARDFLAG_FRIEND_REQUEST	= 0x20
    } 	ZMEDIAITEM_USERCARDFLAG;

typedef 
enum _ZMEDIAITEM_INBOXMSGFLAG
    {
        ZMEDIAITEM_INBOXMSGFLAG_HASBEENREAD	= 0x1,
        ZMEDIAITEM_INBOXMSGFLAG_DELETEPOSTED	= 0x2,
        ZMEDIAITEM_INBOXMSGFLAG_MARKEDFORDELETE	= 0x4,
        ZMEDIAITEM_INBOXMSGFLAG_COMPLETE	= 0x8,
        ZMEDIAITEM_INBOXMSGFLAG_MARKEDREAD	= 0x10
    } 	ZMEDIAITEM_INBOXMSGFLAG;

typedef 
enum _ZMEDIAITEM_CARTFLAG
    {
        ZMEDIAITEM_CARTFLAG_PARTIAL_ALBUMDOWNLOAD	= 0x1,
        ZMEDIAITEM_CARTFLAG_NEEDS_UPDATE	= 0x2
    } 	ZMEDIAITEM_CARTFLAG;

typedef 
enum _ZMEDIAITEM_USERCARDPLAYLIST_TYPE
    {
        ZMEDIAITEM_USERCARD_PLAYLIST_TYPE_NORMAL	= 0,
        ZMEDIAITEM_USERCARD_PLAYLIST_TYPE_FAVORITE	= 1,
        ZMEDIAITEM_USERCARD_PLAYLIST_TYPE_RECENT	= 2,
        ZMEDIAITEM_USERCARD_PLAYLIST_TYPE_TOPARTISTS	= 3
    } 	ZMEDIAITEM_USERCARD_PLAYLIST_TYPE;

typedef 
enum _ZMEDIAITEM_PLAYLIST_TYPE
    {
        ZMEDIAITEM_PLAYLIST_TYPE_INVALID	= -1,
        ZMEDIAITEM_PLAYLIST_TYPE_STATIC	= 0,
        ZMEDIAITEM_PLAYLIST_TYPE_USERCARD	= 1,
        ZMEDIAITEM_PLAYLIST_TYPE_CHANNEL	= 2,
        ZMEDIAITEM_PLAYLIST_TYPE_INBOX	= 3,
        ZMEDIAITEM_PLAYLIST_TYPE_PICTURETAG	= 4,
        ZMEDIAITEM_PLAYLIST_TYPE_PICTUREALBUM	= 5
    } 	ZMEDIAITEM_PLAYLIST_TYPE;

typedef struct _ZPlaylistEntry
    {
    ZMEDIAITEM zmi;
    GUID guidItemId;
    } 	ZPlaylistEntry;

typedef 
enum _ZMEDIAITEM_CHANNEL_STATUS
    {
        ZMEDIAITEM_CHANNEL_STATUS_INVALID	= -1,
        ZMEDIAITEM_CHANNEL_STATUS_COMPLETE	= 0,
        ZMEDIAITEM_CHANNEL_STATUS_INCOMPLETE	= 1,
        ZMEDIAITEM_CHANNEL_STATUS_RETIRED	= 2,
        ZMEDIAITEM_CHANNEL_STATUS_STALE	= 3,
        ZMEDIAITEM_CHANNEL_STATUS_ERROR	= 4
    } 	ZMEDIAITEM_CHANNEL_STATUS;

typedef 
enum _ZMEDIAITEM_CLIP_TYPE
    {
        ZMEDIAITEM_CLIP_TYPE_UNDEFINED	= -1,
        ZMEDIAITEM_CLIP_TYPE_STD_TRACK	= 0,
        ZMEDIAITEM_CLIP_TYPE_30SEC	= 1,
        ZMEDIAITEM_CLIP_TYPE_NOCLIP	= 2,
        ZMEDIAITEM_CLIP_TYPE_STREAM	= 3
    } 	ZMEDIAITEM_CLIP_TYPE;

typedef 
enum _ZMEDIAITEM_ACTIONFLAGS
    {
        ZMEDIAITEM_ACTIONFLAGS_NONE	= 0,
        ZMEDIAITEM_ACTIONFLAGS_PLAY	= 0x1,
        ZMEDIAITEM_ACTIONFLAGS_BUY	= 0x2,
        ZMEDIAITEM_ACTIONFLAGS_ADDTOCOLLECTION	= 0x4
    } 	ZMEDIAITEM_ACTIONFLAGS;

typedef 
enum _ZMEDIAITEM_ACQUIRED_TYPE
    {
        ZMEDIAITEM_FLAG_CAPTURED_ON_DEVICE	= 0x1,
        ZMEDIAITEM_FLAG_RECEIVED_ON_DEVICE	= 0x2,
        ZMEDIAITEM_FLAG_PRELOADED_ON_DEVICE	= 0x3
    } 	ZMEDIAITEM_ACQUIRED_TYPE;

typedef 
enum _ZMEDIAITEM_LICENSESTATE
    {
        ZMEDIAITEM_LICENSESTATE_NONE	= 0,
        ZMEDIAITEM_LICENSESTATE_UNLIMITED	= 1,
        ZMEDIAITEM_LICENSESTATE_USEUNTIL	= 2,
        ZMEDIAITEM_LICENSESTATE_USEONCEGOODFOR24	= 3
    } 	ZMEDIAITEM_LICENSESTATE;

typedef 
enum _ZMEDIAITEM_STREAMSTATUS
    {
        ZMEDIAITEM_STREAMSTATUS_INVALID	= 0,
        ZMEDIAITEM_STREAMSTATUS_NOTSTARTED	= ( ZMEDIAITEM_STREAMSTATUS_INVALID + 1 ) ,
        ZMEDIAITEM_STREAMSTATUS_FETCHING	= ( ZMEDIAITEM_STREAMSTATUS_NOTSTARTED + 1 ) ,
        ZMEDIAITEM_STREAMSTATUS_READY	= ( ZMEDIAITEM_STREAMSTATUS_FETCHING + 1 ) ,
        ZMEDIAITEM_STREAMSTATUS_FETCHED_URL	= ( ZMEDIAITEM_STREAMSTATUS_READY + 1 ) ,
        ZMEDIAITEM_STREAMSTATUS_FETCHED_URL_LICENSE	= ( ZMEDIAITEM_STREAMSTATUS_FETCHED_URL + 1 ) ,
        ZMEDIAITEM_STREAMSTATUS_FAILED	= ( ZMEDIAITEM_STREAMSTATUS_FETCHED_URL_LICENSE + 1 ) ,
        _ZMEDIAITEM_STREAMSTATUS_COUNT	= ( ZMEDIAITEM_STREAMSTATUS_FAILED + 1 ) 
    } 	ZMEDIAITEM_STREAMSTATUS;

typedef 
enum _SmartDjMixState
    {
        SMARTDJMIXSTATE_IDLE	= 0,
        SMARTDJMIXSTATE_GENERATING_LOCAL	= ( SMARTDJMIXSTATE_IDLE + 1 ) ,
        SMARTDJMIXSTATE_GENERATING_MIXED	= ( SMARTDJMIXSTATE_GENERATING_LOCAL + 1 ) ,
        SMARTDJMIXSTATE_GENERATING_MARKETPLACE	= ( SMARTDJMIXSTATE_GENERATING_MIXED + 1 ) ,
        SMARTDJMIXSTATE_ERROR	= ( SMARTDJMIXSTATE_GENERATING_MARKETPLACE + 1 ) 
    } 	SmartDjMixState;

typedef struct _SmartDjStatus
    {
    SmartDjMixState eMixState;
    HRESULT hrResult;
    } 	SmartDjStatus;

typedef struct _ZMEDIAITEM_DSS_ATTRIBUTES
    {
    ULONG eTokenUsageType;
    ULONG eSharePermission;
    ULONG eShareMode;
    ULONG eShareTargetType;
    /* [string] */ LPCWSTR pcwszShareTarget;
    } 	ZMEDIAITEM_DSS_ATTRIBUTES;

typedef /* [v1_enum] */ 
enum _ZMEDIALIB_STORAGELOCATION_INDEXID
    {
        ZMEDIALIB_STORAGELOCATION_INDEXID_INVALID	= -1,
        ZMEDIALIB_STORAGELOCATION_INDEXID_CLOUD	= 0,
        ZMEDIALIB_STORAGELOCATION_INDEXID_INTERNAL	= 1,
        ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_0	= 2,
        ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_1	= 3,
        ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_2	= 4,
        ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_3	= 5,
        _ZMEDIALIB_STORAGELOCATION_INDEXID_COUNT	= 6
    } 	ZMEDIALIB_STORAGELOCATION_INDEXID;

typedef 
enum _ZMEDIALIB_STORAGELOCATION_FLAG
    {
        ZMEDIALIB_STORAGELOCATION_FLAG_NONE	= 0,
        ZMEDIALIB_STORAGELOCATION_FLAG_CLOUD	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_CLOUD ) ,
        ZMEDIALIB_STORAGELOCATION_FLAG_INTERNAL	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_INTERNAL ) ,
        ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_0	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_0 ) ,
        ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_1	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_1 ) ,
        ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_2	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_2 ) ,
        ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_3	= ( 1 << ZMEDIALIB_STORAGELOCATION_INDEXID_EXTERNAL_3 ) 
    } 	ZMEDIALIB_STORAGELOCATION_FLAG;

typedef 
enum _ZMEDIALIB_STORAGE_TYPE
    {
        ZMEDIALIB_STORAGE_TYPE_INTERNAL	= 0,
        ZMEDIALIB_STORAGE_TYPE_EXTERNAL	= ( ZMEDIALIB_STORAGE_TYPE_INTERNAL + 1 ) 
    } 	ZMEDIALIB_STORAGE_TYPE;

typedef 
enum _ZMEDIALIB_STORAGE_FILTER
    {
        ZMEDIALIB_STORAGE_FILTER_NONE	= 0,
        ZMEDIALIB_STORAGE_FILTER_INTERNAL	= ( ZMEDIALIB_STORAGE_FILTER_NONE + 1 ) ,
        ZMEDIALIB_STORAGE_FILTER_EXTERNAL	= ( ZMEDIALIB_STORAGE_FILTER_INTERNAL + 1 ) ,
        ZMEDIALIB_STORAGE_FILTER_STREAMING	= ( ZMEDIALIB_STORAGE_FILTER_EXTERNAL + 1 ) ,
        ZMEDIALIB_STORAGE_FILTER_All	= ( ZMEDIALIB_STORAGE_FILTER_STREAMING + 1 ) 
    } 	ZMEDIALIB_STORAGE_FILTER;

#define ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL (ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_0 | \
                                                            ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_1 | \
                                                            ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_2 | \
                                                            ZMEDIALIB_STORAGELOCATION_FLAG_EXTERNAL_3)
#define ZMEDIALIB_STORAGELOCATION_INDEXID_TO_FLAG(indexId) ( 1 << indexId )
#define ZMEDIALIB_STORAGELOCATION_INDEXID_TO_MIDX(indexId) ( indexId + MIDX_ALL_ITEMS_STORAGELOCATION_CLOUD )
#define ZMEDIALIB_STORAGELOCATION_FLAG_CLOUD_MASK (ZMEDIALIB_STORAGELOCATION_FLAG_CLOUD)
static const GUID ZMEDIALIB_STORAGELOCATION_CLOUD_STORAGEID = { 0xef65826c, 0xc40a, 0x4a69, { 0xae, 0xaa, 0x93, 0xb9, 0xce, 0xa3, 0x10, 0xfc } };
static const GUID ZMEDIALIB_STORAGELOCATION_INTERNAL_STORAGEID = { 0x1ef4b8c6, 0xf38c, 0x4c89, { 0x94, 0xd4, 0x4a, 0xbe, 0x76, 0x4, 0xfb, 0x48 } };
typedef 
enum _ZMEDIALIB_SAVESONGOPERATION
    {
        ZMEDIALIB_SAVESONGOPERATION_COPY	= 0,
        ZMEDIALIB_SAVESONGOPERATION_MOVE	= 1
    } 	ZMEDIALIB_SAVESONGOPERATION;

typedef struct _ZMEDIALIB_SONGMETADATA
    {
    /* [string] */ LPCWSTR pwszName;
    DWORD dwDurationMSec;
    /* [string] */ LPCWSTR pwszArtistName;
    /* [string] */ LPCWSTR pwszGenreName;
    /* [string] */ LPCWSTR pwszAlbumName;
    DWORD dwTrackNumber;
    /* [string] */ LPCWSTR pwszAlbumArtistName;
    /* [string] */ LPCWSTR pwszAlbumReleaseDate;
    /* [string] */ LPCWSTR pwszAlbumArtToken;
    /* [string] */ LPCWSTR pwszArtistBackgroundToken;
    /* [string] */ LPCWSTR pwszAlbumArtistBackgroundToken;
    } 	ZMEDIALIB_SONGMETADATA;

typedef 
enum _ZMEDIALIB_SAVEUGCOPERATION
    {
        ZMEDIALIB_SAVEUGCOPERATION_NOOP	= 0,
        ZMEDIALIB_SAVEUGCOPERATION_COPY	= 1,
        ZMEDIALIB_SAVEUGCOPERATION_MOVE	= 2
    } 	ZMEDIALIB_SAVEUGCOPERATION;

typedef struct _ZMEDIALIB_UGCMETADATA
    {
    /* [string] */ LPCWSTR pwszName;
    /* [string] */ LPCWSTR pwszArtFileToken;
    /* [string] */ LPCWSTR pwszSmallArtFileToken;
    FILETIME ft;
    DWORD dwWidth;
    DWORD dwHeight;
    DWORD dwOrientation;
    DWORD dwLongitude;
    DWORD dwLatitude;
    DWORD dwAltitude;
    DWORD dwDurationMSec;
    DWORD dwRating;
    DWORD dwRatingPercent;
    } 	ZMEDIALIB_UGCMETADATA;

typedef struct _ZMEDIALIB_CHANGE_RECORD
    {
    ULONG revision;
    BOOL itemDeleted;
    ZMEDIAITEM zmi;
    GUID mediaId;
    GUID persistentUniqueId;
    } 	ZMEDIALIB_CHANGE_RECORD;

typedef 
enum _ZMEDIA_NOTIFICATIONTYPE
    {
        ZMEDIA_NOTIFICATIONTYPE_NONE	= 0,
        ZMEDIA_NOTIFICATIONTYPE_ADDFILE	= ( ZMEDIA_NOTIFICATIONTYPE_NONE + 1 ) ,
        ZMEDIA_NOTIFICATIONTYPE_DELETEFILE	= ( ZMEDIA_NOTIFICATIONTYPE_ADDFILE + 1 ) ,
        ZMEDIA_NOTIFICATIONTYPE_CHANGEFILE	= ( ZMEDIA_NOTIFICATIONTYPE_DELETEFILE + 1 ) ,
        ZMEDIA_NOTIFICATIONTYPE_MOVEFILEFOLDER	= ( ZMEDIA_NOTIFICATIONTYPE_CHANGEFILE + 1 ) ,
        ZMEDIA_NOTIFICATIONTYPE_NOTIFICATIONSMISSED	= ( ZMEDIA_NOTIFICATIONTYPE_MOVEFILEFOLDER + 1 ) ,
        ZMEDIA_NOTIFICATIONTYPE_ALL	= ( ZMEDIA_NOTIFICATIONTYPE_NOTIFICATIONSMISSED + 1 ) 
    } 	ZMEDIA_NOTIFICATIONTYPE;



extern RPC_IF_HANDLE __MIDL_itf_zmedialibtypes_0000_0000_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_zmedialibtypes_0000_0000_v0_0_s_ifspec;

/* Additional Prototypes for ALL interfaces */

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif


