/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

Module Name:

    NetAdapterPacket.h

Abstract:

    Wrapper functions to access NET_PACKETs from a NET_RING_BUFFER

Environment:

    kernel mode only

Revision History:

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _NETADAPTERPACKET_H_
#define _NETADAPTERPACKET_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START




typedef PCWDF_OBJECT_CONTEXT_TYPE_INFO PCNET_CONTEXT_TYPE_INFO;
typedef struct NET_PACKET_CONTEXT_TOKEN *PNET_PACKET_CONTEXT_TOKEN;

typedef struct _NET_PACKET_CONTEXT_ATTRIBUTES *PNET_PACKET_CONTEXT_ATTRIBUTES;
typedef struct _NET_PACKET_CONTEXT_ATTRIBUTES
{
    //
    // Size of structure
    //
    ULONG Size;

    //
    // If not zero, context size to use when allocating
    // packet context
    //
    size_t ContextSizeOverride;

    //
    // Context type info
    //
    PCNET_CONTEXT_TYPE_INFO ContextTypeInfo;

} NET_PACKET_CONTEXT_ATTRIBUTES, *PNET_PACKET_CONTEXT_ATTRIBUTES;

#define NET_PACKET_CONTEXT_ATTRIBUTES_INIT_TYPE(_packetcontextattributes, _contexttype)     \
    RtlZeroMemory((_packetcontextattributes), sizeof(NET_PACKET_CONTEXT_ATTRIBUTES));       \
    (_packetcontextattributes)->Size = sizeof(NET_PACKET_CONTEXT_ATTRIBUTES);               \
    (_packetcontextattributes)->ContextTypeInfo = WDF_GET_CONTEXT_TYPE_INFO(_contexttype);  \

#define NET_PACKET_DECLARE_CASTING_FUNCTION(_contexttype, _castingfunction)     \
                                                                                \
WDF_EXTERN_C                                                                    \
__drv_aliasesMem                                                                \
WDF_TYPE_NAME_POINTER_TYPE(_contexttype)                                        \
FORCEINLINE                                                                     \
_castingfunction(                                                               \
   _In_ NET_PACKET* NetPacket                                                   \
   )                                                                            \
{                                                                               \
    return (WDF_TYPE_NAME_POINTER_TYPE(_contexttype))                           \
        NetPacketGetTypedContext(                                               \
            NetPacket,                                                          \
            WDF_GET_CONTEXT_TYPE_INFO(_contexttype)->UniqueType                 \
            );                                                                  \
}                                                                               \

#define NET_PACKET_DECLARE_CASTING_FUNCTION_FROM_TOKEN(_contexttype, _castingfunction)      \
                                                                                            \
WDF_EXTERN_C                                                                                \
__drv_aliasesMem                                                                            \
WDF_TYPE_NAME_POINTER_TYPE(_contexttype)                                                    \
FORCEINLINE                                                                                 \
_castingfunction##FromToken(                                                                \
   _In_ NET_PACKET* NetPacket,                                                              \
   _In_ PNET_PACKET_CONTEXT_TOKEN Token                                                     \
   )                                                                                        \
{                                                                                           \
    return (WDF_TYPE_NAME_POINTER_TYPE(_contexttype))                                       \
        NetPacketGetContextFromToken(                                                       \
            NetPacket,                                                                      \
            Token                                                                           \
            );                                                                              \
}                                                                                           \


#define NET_PACKET_DECLARE_CONTEXT_TYPE_WITH_NAME(_contexttype, _castingfunction)   \
                                                                                    \
WDF_DECLARE_TYPE_AND_GLOBALS(                                                       \
    _contexttype,                                                                   \
    WDF_GET_CONTEXT_TYPE_INFO(_contexttype),                                        \
    NULL,                                                                           \
    WDF_TYPE_DEFAULT_SECTION_NAME)                                                  \
                                                                                    \
NET_PACKET_DECLARE_CASTING_FUNCTION(_contexttype, _castingfunction)                 \
NET_PACKET_DECLARE_CASTING_FUNCTION_FROM_TOKEN(_contexttype, _castingfunction)      \

__inline
NET_PACKET *
NetRingBufferGetPacketAtIndex(
    _In_ NET_RING_BUFFER *RingBuffer,
    _In_ UINT32 Index
    )
{
    return (NET_PACKET*)NetRingBufferGetElementAtIndex(RingBuffer, Index);
}

__inline
NET_PACKET *
NetRingBufferGetNextPacket(
    _In_ NET_RING_BUFFER *RingBuffer
    )
{
    UINT32 NextIndex = RingBuffer->NextIndex;

    if (NextIndex == RingBuffer->EndIndex)
        return NULL;

    return NetRingBufferGetPacketAtIndex(RingBuffer, NextIndex);
}

__inline
NET_PACKET *
NetRingBufferAdvanceNextPacket(
    _In_ NET_RING_BUFFER *RingBuffer
    )
{
    UINT32 NextIndex = RingBuffer->NextIndex;

    if (NextIndex == RingBuffer->EndIndex)
        return NULL;

    RingBuffer->NextIndex = NetRingBufferIncrementIndex(RingBuffer, NextIndex);

    return NetRingBufferGetPacketAtIndex(RingBuffer, NextIndex);
}

__inline
VOID
NetRingBufferReturnCompletedPacketsThroughIndex(
    _In_ NET_RING_BUFFER *RingBuffer,
    _In_ UINT32 EndIndex
    )
{
    UINT32 i;

    for (i = RingBuffer->BeginIndex; i != EndIndex; i = NetRingBufferIncrementIndex(RingBuffer, i))
    {
        NET_PACKET *packet = NetRingBufferGetPacketAtIndex(RingBuffer, i);
        NET_PACKET_FRAGMENT *fragment;
        BOOLEAN isFirstFragmentOfPacket = TRUE;

        for (fragment = &packet->Data; fragment; fragment = NET_PACKET_FRAGMENT_GET_NEXT(fragment))
        {
            if (isFirstFragmentOfPacket && !fragment->Completed)
            {
                RingBuffer->BeginIndex = i;
                return;
            }

            if (fragment->LastPacketOfChain)
                break;

            isFirstFragmentOfPacket = (BOOLEAN)fragment->LastFragmentOfFrame;
        }
    }

    RingBuffer->BeginIndex = i;
}

__inline
VOID
NetRingBufferReturnCompletedPackets(
    _In_ NET_RING_BUFFER *RingBuffer
    )
{
    NetRingBufferReturnCompletedPacketsThroughIndex(RingBuffer, RingBuffer->NextIndex);
}

//
// NET Function: NetPacketGetTypedContext
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
PVOID
(*PFN_NETPACKETGETTYPEDCONTEXT)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NET_PACKET* NetPacket,
    _In_
    PCNET_CONTEXT_TYPE_INFO TypeInfo
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
PVOID
FORCEINLINE
NetPacketGetTypedContext(
    _In_
    NET_PACKET* NetPacket,
    _In_
    PCNET_CONTEXT_TYPE_INFO TypeInfo
    )
{
    return ((PFN_NETPACKETGETTYPEDCONTEXT) NetFunctions[NetPacketGetTypedContextTableIndex])(NetDriverGlobals, NetPacket, TypeInfo);
}

//
// NET Function: NetPacketGetContextFromToken
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
PVOID
(*PFN_NETPACKETGETCONTEXTFROMTOKEN)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NET_PACKET* NetPacket,
    _In_
    PNET_PACKET_CONTEXT_TOKEN Token
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
PVOID
FORCEINLINE
NetPacketGetContextFromToken(
    _In_
    NET_PACKET* NetPacket,
    _In_
    PNET_PACKET_CONTEXT_TOKEN Token
    )
{
    return ((PFN_NETPACKETGETCONTEXTFROMTOKEN) NetFunctions[NetPacketGetContextFromTokenTableIndex])(NetDriverGlobals, NetPacket, Token);
}



WDF_EXTERN_C_END

#endif // _NETADAPTERPACKET_H_

