/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

Module Name:

    NetAdapterCxTypes.h

Abstract:

    This is the types for the NetAdapterCx driver

Environment:

    kernel mode only

Revision History:

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _NETADAPTERCXTYPES_H_
#define _NETADAPTERCXTYPES_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



//
// core handles
//
DECLARE_HANDLE( NETADAPTER );
DECLARE_HANDLE( NETCONFIGURATION );
DECLARE_HANDLE( NETREQUEST );
DECLARE_HANDLE( NETREQUESTQUEUE );
DECLARE_HANDLE( NETBUFFERLISTCOLLECTION );
DECLARE_HANDLE( NETTXQUEUE );
DECLARE_HANDLE( NETRXQUEUE );
DECLARE_HANDLE( NETPOWERSETTINGS );

typedef struct NETADAPTER_INIT *PNETADAPTER_INIT;

typedef struct _NET_DRIVER_GLOBALS {
    ULONG Unused;
} NET_DRIVER_GLOBALS, *PNET_DRIVER_GLOBALS;

typedef VOID (*NETFUNC) (VOID);
extern NETFUNC NetFunctions[];


WDF_EXTERN_C_END

#endif // _NETADAPTERCXTYPES_H_

