/*++

Copyright (c) Microsoft Corporation. All Rights Reserved.

Module Name:
    Udecx.h

Abstract:
    The Udecx client includes this file in its code. 
    This file includes all the necessary files needed for the Udecx client.

Revision History:

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UDECX_H_
#define _UDECX_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



#include "UdecxTypes.h"
#include "UdecxFuncEnum.h"
#include "UdecxWdfDevice.h"
#include "UdecxUsbDevice.h"
#include "UdecxUsbEndpoint.h"
#include "UdecxUrb.h"





WDF_EXTERN_C_END

#endif // _UDECX_H_

