/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UrsCx.h

Abstract:

    Main header file for USB Role Switch class extension client.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _URSCX_H_
#define _URSCX_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



typedef VOID (*URSFUNC) (VOID);
extern URSFUNC UrsFunctions[];

#include "UrsTypes.h"
#include "UrsGlobals.h"
#include "UrsFuncEnum.h"
#include "UrsDevice.h"




WDF_EXTERN_C_END

#endif // _URSCX_H_

