

/* this ALWAYS GENERATED file contains the definitions for the interfaces */


 /* File created by MIDL compiler version 8.01.0622 */
/* @@MIDL_FILE_HEADING(  ) */



/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include "rpc.h"
#include "rpcndr.h"

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */


#ifndef __zmediaqueuetypes_h__
#define __zmediaqueuetypes_h__

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/* Forward Declarations */ 

/* header files for imported files */
#include "wtypes.h"
#include "oaidl.h"
#include "ZMediaLibTypes.h"

#ifdef __cplusplus
extern "C"{
#endif 


/* interface __MIDL_itf_zmediaqueuetypes_0000_0000 */
/* [local] */ 

#define	ZMEDIAQUEUE_ITEMINDEX_DEFAULT	( 0xffffffff )

#define	ZMEDIAQUEUE_CLIENTQUEUE_COUNT	( 10 )

typedef /* [v1_enum] */ 
enum _ZMEDIAQUEUE
    {
        ZMEDIAQUEUE_INVALID	= 0,
        ZMEDIAQUEUE_AUDIO	= ( ZMEDIAQUEUE_INVALID + 1 ) ,
        ZMEDIAQUEUE_VIDEO	= ( ZMEDIAQUEUE_AUDIO + 1 ) ,
        ZMEDIAQUEUE_AUDIOPODCAST	= ( ZMEDIAQUEUE_VIDEO + 1 ) ,
        ZMEDIAQUEUE_TRANSIENTAUDIO	= ( ZMEDIAQUEUE_AUDIOPODCAST + 1 ) ,
        ZMEDIAQUEUE_RADIO	= ( ZMEDIAQUEUE_TRANSIENTAUDIO + 1 ) ,
        ZMEDIAQUEUE_CLIENTQUEUE_FIRST	= ( ZMEDIAQUEUE_RADIO + 1 ) ,
        ZMEDIAQUEUE_CLIENTQUEUE_LAST	= ( ( ZMEDIAQUEUE_CLIENTQUEUE_FIRST + ZMEDIAQUEUE_CLIENTQUEUE_COUNT )  - 1 ) ,
        _ZMEDIAQUEUE_COUNT	= ( ZMEDIAQUEUE_CLIENTQUEUE_LAST + 1 ) ,
        ZMEDIAQUEUE_ALL	= 0xffffffff,
        ZMEDIAQUEUE_MEDIASERVICE	= 0xfffffffe
    } 	ZMEDIAQUEUE;

typedef 
enum _ZMEDIAQUEUE_CLIENTQUEUETYPE
    {
        ZMEDIAQUEUE_CLIENTQUEUETYPE_INVALID	= 0,
        ZMEDIAQUEUE_CLIENTQUEUETYPE_AUDIO	= ( ZMEDIAQUEUE_CLIENTQUEUETYPE_INVALID + 1 ) ,
        ZMEDIAQUEUE_CLIENTQUEUETYPE_VIDEO	= ( ZMEDIAQUEUE_CLIENTQUEUETYPE_AUDIO + 1 ) ,
        ZMEDIAQUEUE_CLIENTQUEUETYPE_BACKGROUND_AUDIO	= ( ZMEDIAQUEUE_CLIENTQUEUETYPE_VIDEO + 1 ) ,
        ZMEDIAQUEUE_CLIENTQUEUETYPE_AMBIGUOUS	= ( ZMEDIAQUEUE_CLIENTQUEUETYPE_BACKGROUND_AUDIO + 1 ) 
    } 	ZMEDIAQUEUE_CLIENTQUEUETYPE;

typedef 
enum _ZMEDIAQUEUE_MASK
    {
        ZMEDIAQUEUE_MASK_NONE	= 0,
        ZMEDIAQUEUE_MASK_AUDIO	= ( 1 << ZMEDIAQUEUE_AUDIO ) ,
        ZMEDIAQUEUE_MASK_VIDEO	= ( 1 << ZMEDIAQUEUE_VIDEO ) ,
        ZMEDIAQUEUE_MASK_AUDIOPODCASTS	= ( 1 << ZMEDIAQUEUE_AUDIOPODCAST ) ,
        ZMEDIAQUEUE_MASK_TRANSIENTAUDIO	= ( 1 << ZMEDIAQUEUE_TRANSIENTAUDIO ) ,
        ZMEDIAQUEUE_MASK_RADIO	= ( 1 << ZMEDIAQUEUE_RADIO ) 
    } 	ZMEDIAQUEUE_MASK;

typedef 
enum _ZMEDIAQUEUE_NOTIFICATION
    {
        ZMEDIAQUEUE_NOTIFICATION_INVALID	= 0,
        ZMEDIAQUEUE_NOTIFICATION_PLAYSTATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_INVALID + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_PLAYPOSITIONCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_PLAYSTATECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_PLAYRATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_PLAYPOSITIONCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_PLAYFLAGSCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_PLAYRATECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_PLAYFLAGSCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMREADY	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMCOMPLETE	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMREADY + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMVIEWWINDOWEXPIRED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMCOMPLETE + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMVIEWINDOWCOUNTEXCEEDED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMVIEWWINDOWEXPIRED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMEXPIRED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMVIEWINDOWCOUNTEXCEEDED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMALREADYRECEIVED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMEXPIRED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_CONTENTSCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMALREADYRECEIVED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_VOLUMECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_CONTENTSCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_MUTESTATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_VOLUMECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_FREQUENCYCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_MUTESTATECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ARTCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_FREQUENCYCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_CHAPTERCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_ARTCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_METADATACHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_CHAPTERCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_SHOWSTATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_METADATACHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ERROR	= ( ZMEDIAQUEUE_NOTIFICATION_SHOWSTATECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_RDSREADY	= ( ZMEDIAQUEUE_NOTIFICATION_ERROR + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ANTENNASTATUSCHANGE	= ( ZMEDIAQUEUE_NOTIFICATION_RDSREADY + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMBUFFERING	= ( ZMEDIAQUEUE_NOTIFICATION_ANTENNASTATUSCHANGE + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_VIDEOSIZECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMBUFFERING + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_DRM_NEEDLICENSE	= ( ZMEDIAQUEUE_NOTIFICATION_VIDEOSIZECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_DRM_STATUS	= ( ZMEDIAQUEUE_NOTIFICATION_DRM_NEEDLICENSE + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_VIDEORESOURCELOST	= ( ZMEDIAQUEUE_NOTIFICATION_DRM_STATUS + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMERROR	= ( ZMEDIAQUEUE_NOTIFICATION_VIDEORESOURCELOST + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_UNSOLICITEDPLAYSTATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMERROR + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_CLIENTQUEUEFORURL	= ( ZMEDIAQUEUE_NOTIFICATION_UNSOLICITEDPLAYSTATECHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_SMARTDJSTATUSCHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_CLIENTQUEUEFORURL + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_EXTENDEDAUDIO	= ( ZMEDIAQUEUE_NOTIFICATION_SMARTDJSTATUSCHANGED + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_SHOWSYSTEMPLAYCONTROL	= ( ZMEDIAQUEUE_NOTIFICATION_EXTENDEDAUDIO + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_BACKGROUNDARTAVAILABLE	= ( ZMEDIAQUEUE_NOTIFICATION_SHOWSYSTEMPLAYCONTROL + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_ITEMCONNECTING	= ( ZMEDIAQUEUE_NOTIFICATION_BACKGROUNDARTAVAILABLE + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_DRM_DECRYPTOR_SETUP	= ( ZMEDIAQUEUE_NOTIFICATION_ITEMCONNECTING + 1 ) ,
        ZMEDIAQUEUE_NOTIFICATION_SYSTEMRESTARTSTATECHANGED	= ( ZMEDIAQUEUE_NOTIFICATION_DRM_DECRYPTOR_SETUP + 1 ) ,
        _ZMEDIAQUEUE_NOTIFICATION_COUNT	= ( ZMEDIAQUEUE_NOTIFICATION_SYSTEMRESTARTSTATECHANGED + 1 ) 
    } 	ZMEDIAQUEUE_NOTIFICATION;

typedef 
enum _ZMEDIAQUEUE_PLAYFLAGS
    {
        ZMEDIAQUEUE_PLAYFLAGS_SHUFFLE	= 0x1,
        ZMEDIAQUEUE_PLAYFLAGS_REPEAT	= 0x2,
        ZMEDIAQUEUE_PLAYFLAGS_REPEAT_SINGLE	= 0x4
    } 	ZMEDIAQUEUE_PLAYFLAGS;

typedef 
enum _ZMEDIAQUEUE_CONTENTSCHANGED
    {
        ZMEDIAQUEUE_CONTENTSCHANGED_ITEMS_UNCHANGED	= 0,
        ZMEDIAQUEUE_CONTENTSCHANGED_ITEMS_CHANGED	= ( ZMEDIAQUEUE_CONTENTSCHANGED_ITEMS_UNCHANGED + 1 ) 
    } 	ZMEDIAQUEUE_CONTENTSCHANGED;

typedef 
enum _ZMEDIAQUEUE_MOVEFLAGS
    {
        ZMEDIAQUEUE_MOVEFLAGS_NONE	= 0,
        ZMEDIAQUEUE_MOVEFLAGS_PRESERVEBOOKMARK	= 0x1,
        ZMEDIAQUEUE_MOVEFLAGS_STARTATBOOKMARK	= 0x2,
        ZMEDIAQUEUE_MOVEFLAGS_WRAP	= 0x4,
        ZMEDIAQUEUE_MOVEFLAGS_ASYNC	= 0x8000
    } 	ZMEDIAQUEUE_MOVEFLAGS;

typedef 
enum _ZMEDIAQUEUE_CLEANUP
    {
        ZMEDIAQUEUE_CLEANUP_NONE	= 0,
        ZMEDIAQUEUE_CLEANUP_PARTIAL	= ( ZMEDIAQUEUE_CLEANUP_NONE + 1 ) ,
        ZMEDIAQUEUE_CLEANUP_ALL	= ( ZMEDIAQUEUE_CLEANUP_PARTIAL + 1 ) 
    } 	ZMEDIAQUEUE_CLEANUP;

typedef 
enum _ZMEDIAQUEUE_RADIOREGION
    {
        ZMEDIAQUEUE_RADIOREGION_INVALID	= 0,
        ZMEDIAQUEUE_RADIOREGION_USA	= ( ZMEDIAQUEUE_RADIOREGION_INVALID + 1 ) ,
        ZMEDIAQUEUE_RADIOREGION_EUROPE	= ( ZMEDIAQUEUE_RADIOREGION_USA + 1 ) ,
        ZMEDIAQUEUE_RADIOREGION_JAPAN	= ( ZMEDIAQUEUE_RADIOREGION_EUROPE + 1 ) ,
        _ZMEDIAQUEUE_RADIOREGION_COUNT	= ( ZMEDIAQUEUE_RADIOREGION_JAPAN + 1 ) 
    } 	ZMEDIAQUEUE_RADIOREGION;

typedef struct _ZMEDIAQUEUE_RADIO_RTPLUS_TAG
    {
    BOOL fRTPlusItemToggleBit;
    BOOL fRTPlusItemRunningBit;
    BYTE bContentType_tag1;
    BYTE bStartMarker_tag1;
    BYTE bLengthMarker_tag1;
    BYTE bContentType_tag2;
    BYTE bStartMarker_tag2;
    BYTE bLengthMarker_tag2;
    } 	ZMEDIAQUEUE_RADIO_RTPLUS_TAG;

typedef 
enum _ZMEDIAQUEUE_RADIO_RTPLUS_CLASS
    {
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_TITLE	= 1,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_ALBUM	= 2,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_TRACKNUMBER	= 3,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_ARTIST	= 4,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_COMPOSITION	= 5,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_MOVEMENT	= 6,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_CONDUCTOR	= 7,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_COMPOSER	= 8,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_BAND	= 9,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_COMMENT	= 10,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_ITEM_GENRE	= 11,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_NEWS	= 12,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_NEWS_LOCAL	= 13,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_STOCKMARKET	= 14,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_SPORT	= 15,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_LOTTERY	= 16,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_HOROSCOPE	= 17,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_DAILY_DIVERSION	= 18,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_HEALTH	= 19,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_EVENT	= 20,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_SCENE	= 21,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_CINEMA	= 22,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_TV	= 23,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_DATE_TIME	= 24,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_WEATHER	= 25,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_TRAFFIC	= 26,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_ALARM	= 27,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_ADVERTISEMENT	= 28,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_URL	= 29,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INFO_OTHER	= 30,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_STATIONNAME_SHORT	= 31,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_STATIONNAME_LONG	= 32,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_NOW	= 33,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_NEXT	= 34,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_PART	= 35,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_HOST	= 36,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_EDITORIAL_STAFF	= 37,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_FREQUENCY	= 38,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_HOMEPAGE	= 39,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_PROGRAM_SUBCHANNEL	= 40,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_PHONE_HOTLINE	= 41,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_PHONE_STUDIO	= 42,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_PHONE_OTHER	= 43,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_SMS_STUDIO	= 44,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_SMS_OTHER	= 45,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_EMAIL_HOTLINE	= 46,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_EMAIL_STUDIO	= 47,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_EMAIL_OTHER	= 48,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_MMS_OTHER	= 49,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_CHAT	= 50,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_CHAT_CENTER	= 51,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_VOTE_QUESTION	= 52,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_INTERACTIVITY_VOTE_CENTER	= 53,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_DESCRIPTOR_PLACE	= 59,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_DESCRIPTOR_APPOINTMENT	= 60,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_DESCRIPTOR_IDENTIFIER	= 61,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_DESCRIPTOR_PURCHASE	= 62,
        ZMEDIAQUEUE_RADIO_RTPLUS_CLASS_DESCRIPTOR_GET_DATA	= 63
    } 	ZMEDIAQUEUE_RADIO_RTPLUS_CLASS;

typedef struct _ZMEDIAQUEUE_RADIO_IDI
    {
    DWORD dwData[ 16 ];
    BOOL fDataReady[ 16 ];
    } 	ZMEDIAQUEUE_RADIO_IDI;

typedef struct _ZMEDIAQUEUE_RADIO_STATION_INFO
    {
    WCHAR name[ 9 ];
    } 	ZMEDIAQUEUE_RADIO_STATION_INFO;

typedef 
enum _ZMEDIAQUEUE_PLAYSTATE
    {
        ZMEDIAQUEUE_PLAYSTATE_INVALID	= 0,
        ZMEDIAQUEUE_PLAYSTATE_UNKNOWN	= ( ZMEDIAQUEUE_PLAYSTATE_INVALID + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_LOADING	= ( ZMEDIAQUEUE_PLAYSTATE_UNKNOWN + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_PLAYING	= ( ZMEDIAQUEUE_PLAYSTATE_LOADING + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_PAUSED	= ( ZMEDIAQUEUE_PLAYSTATE_PLAYING + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_STOPPED	= ( ZMEDIAQUEUE_PLAYSTATE_PAUSED + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_FASTFORWARDING	= ( ZMEDIAQUEUE_PLAYSTATE_STOPPED + 1 ) ,
        ZMEDIAQUEUE_PLAYSTATE_REWINDING	= ( ZMEDIAQUEUE_PLAYSTATE_FASTFORWARDING + 1 ) ,
        _ZMEDIAQUEUE_PLAYSTATE_COUNT	= ( ZMEDIAQUEUE_PLAYSTATE_REWINDING + 1 ) 
    } 	ZMEDIAQUEUE_PLAYSTATE;

typedef 
enum _ZMEDIAQUEUE_PROGRESSIVEPLAYMODE
    {
        ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_INVALID	= 0,
        ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_OFF	= ( ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_INVALID + 1 ) ,
        ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_FORWARD	= ( ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_OFF + 1 ) ,
        ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_REVERSE	= ( ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_FORWARD + 1 ) ,
        _ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_COUNT	= ( ZMEDIAQUEUE_PROGRESSIVEPLAYMODE_REVERSE + 1 ) 
    } 	ZMEDIAQUEUE_PROGRESSIVEPLAYMODE;

typedef 
enum _MEDIAITEM_VIDEO_ZOOM_MODE
    {
        MEDIAITEM_VIDEO_ZOOM_NONE	= 0,
        MEDIAITEM_VIDEO_ZOOM_WIDE_SCREEN	= ( MEDIAITEM_VIDEO_ZOOM_NONE + 1 ) 
    } 	MEDIAITEM_VIDEO_ZOOM_MODE;

#define	ZMEDIAQUEUE_VIZDATA_FREQSLOTS	( 256 )

#define	ZMEDIAQUEUE_VIZDATA_WAVESLOTS	( 256 )

typedef struct _ZMEDIAQUEUE_VIZDATA
    {
    float rgFreqData[ 256 ];
    float rgWaveData[ 256 ];
    } 	ZMEDIAQUEUE_VIZDATA;

typedef 
enum _ZMEDIAQUEUE_SEEKDIR
    {
        ZMEDIAQUEUE_SEEKDIR_INVALID	= 0,
        ZMEDIAQUEUE_SEEKDIR_DOWN	= ( ZMEDIAQUEUE_SEEKDIR_INVALID + 1 ) ,
        ZMEDIAQUEUE_SEEKDIR_UP	= ( ZMEDIAQUEUE_SEEKDIR_DOWN + 1 ) ,
        _ZMEDIAQUEUE_SEEKDIR_COUNT	= ( ZMEDIAQUEUE_SEEKDIR_UP + 1 ) 
    } 	ZMEDIAQUEUE_SEEKDIR;

typedef 
enum _ZMEDIAQUEUE_STATIONTEXT
    {
        ZMEDIAQUEUE_STATIONTEXT_NAME	= 0,
        ZMEDIAQUEUE_STATIONTEXT_CALLSIGN	= ( ZMEDIAQUEUE_STATIONTEXT_NAME + 1 ) ,
        ZMEDIAQUEUE_STATIONTEXT_DESCRIPTION	= ( ZMEDIAQUEUE_STATIONTEXT_CALLSIGN + 1 ) ,
        _ZMEDIAQUEUE_STATIONTEXT_COUNT	= ( ZMEDIAQUEUE_STATIONTEXT_DESCRIPTION + 1 ) 
    } 	ZMEDIAQUEUE_STATIONTEXT;

typedef 
enum _ZMEDIAQUEUE_STATIONGENRE
    {
        ZMEDIAQUEUE_STATIONGENRE_INVALID	= 0,
        ZMEDIAQUEUE_STATIONGENRE_NEWS	= ( ZMEDIAQUEUE_STATIONGENRE_INVALID + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_INFORMATION	= ( ZMEDIAQUEUE_STATIONGENRE_NEWS + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_SPORTS	= ( ZMEDIAQUEUE_STATIONGENRE_INFORMATION + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_TALK	= ( ZMEDIAQUEUE_STATIONGENRE_SPORTS + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_ROCK	= ( ZMEDIAQUEUE_STATIONGENRE_TALK + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_CLASSICROCK	= ( ZMEDIAQUEUE_STATIONGENRE_ROCK + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_ADULTHITS	= ( ZMEDIAQUEUE_STATIONGENRE_CLASSICROCK + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_SOFTROCK	= ( ZMEDIAQUEUE_STATIONGENRE_ADULTHITS + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_TOP40	= ( ZMEDIAQUEUE_STATIONGENRE_SOFTROCK + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_COUNTRY	= ( ZMEDIAQUEUE_STATIONGENRE_TOP40 + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_OLDIES	= ( ZMEDIAQUEUE_STATIONGENRE_COUNTRY + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_SOFT	= ( ZMEDIAQUEUE_STATIONGENRE_OLDIES + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_NOSTALGIA	= ( ZMEDIAQUEUE_STATIONGENRE_SOFT + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_JAZZ	= ( ZMEDIAQUEUE_STATIONGENRE_NOSTALGIA + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_CLASSICAL	= ( ZMEDIAQUEUE_STATIONGENRE_JAZZ + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_RANDB	= ( ZMEDIAQUEUE_STATIONGENRE_CLASSICAL + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_SOFTRANDB	= ( ZMEDIAQUEUE_STATIONGENRE_RANDB + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_LANGUAGE	= ( ZMEDIAQUEUE_STATIONGENRE_SOFTRANDB + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_RELIGIOUSMUSIC	= ( ZMEDIAQUEUE_STATIONGENRE_LANGUAGE + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_RELIGIOUSTALK	= ( ZMEDIAQUEUE_STATIONGENRE_RELIGIOUSMUSIC + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_PERSONALITY	= ( ZMEDIAQUEUE_STATIONGENRE_RELIGIOUSTALK + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_PUBLIC	= ( ZMEDIAQUEUE_STATIONGENRE_PERSONALITY + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_COLLEGE	= ( ZMEDIAQUEUE_STATIONGENRE_PUBLIC + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED18	= ( ZMEDIAQUEUE_STATIONGENRE_COLLEGE + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED19	= ( _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED18 + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1A	= ( _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED19 + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1B	= ( _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1A + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1C	= ( _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1B + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_WEATHER	= ( _ZMEDIAQUEUE_STATIONGENRE_UNASSIGNED1C + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_EMERGENCYTEST	= ( ZMEDIAQUEUE_STATIONGENRE_WEATHER + 1 ) ,
        ZMEDIAQUEUE_STATIONGENRE_EMERGENCY	= ( ZMEDIAQUEUE_STATIONGENRE_EMERGENCYTEST + 1 ) ,
        _ZMEDIAQUEUE_STATIONGENRE_COUNT	= ( ZMEDIAQUEUE_STATIONGENRE_EMERGENCY + 1 ) 
    } 	ZMEDIAQUEUE_STATIONGENRE;

typedef 
enum _ZMEDIAQUEUE_HDRADIO_STATUS
    {
        ZMEDIAQUEUE_SIGNAL_ANALOG	= 0,
        ZMEDIAQUEUE_SIGNAL_HDLINKING	= 1,
        ZMEDIAQUEUE_SIGNAL_HDDETECTED	= 2
    } 	ZMEDIAQUEUE_HDRADIO_STATUS;

typedef 
enum _ZMEDIAQUEUE_SEEKFLAGS
    {
        ZMEDIAQUEUE_SEEKFLAGS_WRAP	= 0x1
    } 	ZMEDIAQUEUE_SEEKFLAGS;

#define	ZMEDIAQUEUE_MIN_VOLUME	( -10000 )

#define	ZMEDIAQUEUE_MAX_VOLUME	( 0 )

typedef struct _ZMEDIAQUEUE_NOTIFICATIONDATA
    {
    ZMEDIAQUEUE queue;
    ZMEDIAQUEUE_NOTIFICATION notifyCode;
    UINT idxItem1;
    UINT idxItem2;
    UINT param1;
    } 	ZMEDIAQUEUE_NOTIFICATIONDATA;

typedef 
enum _ZMEDIAQUEUE_STREAMDATA_HINTFLAGS
    {
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_NAME	= 0x1,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_ARTIST	= 0x2,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_ALBUM	= 0x4,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_NUMBER	= 0x8,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_EXPLICIT	= 0x10,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_DURATION	= 0x20,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_ARTIST_MEDIAID	= 0x40,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_RIGHT_PREVIEW	= 0x80,
        ZMEDIAQUEUE_STREAMDATA_HINTFLAGS_RIGHT_FULLSTREAM	= 0x100
    } 	ZMEDIAQUEUE_STREAMDATA_HINTFLAGS;

typedef struct _ZMEDIAQUEUE_HDTUNEPARAMS
    {
    ZMEDIAQUEUE_HDRADIO_STATUS hdStatus;
    BYTE ucSubChannels;
    } 	ZMEDIAQUEUE_HDTUNEPARAMS;

typedef struct _ZMEDIAQUEUE_TUNEPARAMS
    {
    int kHz;
    BYTE subChannel;
    ZMEDIAQUEUE_HDTUNEPARAMS HDParams;
    } 	ZMEDIAQUEUE_TUNEPARAMS;

typedef 
enum _ZMEDIAQUEUE_EQUALIZER_PRESET
    {
        ZMEDIAQUEUE_EQUALIZER_PRESET_NONE	= 0,
        ZMEDIAQUEUE_EQUALIZER_PRESET_ACOUSTIC	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_NONE + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_CLASSICAL	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_ACOUSTIC + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_ELECTRONICA	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_CLASSICAL + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_HIPHOP	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_ELECTRONICA + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_JAZZ	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_HIPHOP + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_POP	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_JAZZ + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_ROCK	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_POP + 1 ) ,
        ZMEDIAQUEUE_EQUALIZER_PRESET_DEBUG	= ( ZMEDIAQUEUE_EQUALIZER_PRESET_ROCK + 1 ) 
    } 	ZMEDIAQUEUE_EQUALIZER_PRESET;

typedef 
enum _ZMEDIAQUEUE_FFTRESULTS
    {
        ZMEDIAQUEUE_FFTRESULTS_LINEAR_SCALE_RAW	= 0,
        ZMEDIAQUEUE_FFTRESULTS_LINEAR_SCALE_SMOOTH	= ( ZMEDIAQUEUE_FFTRESULTS_LINEAR_SCALE_RAW + 1 ) ,
        ZMEDIAQUEUE_FFTRESULTS_LOG_SCALE_RAW	= ( ZMEDIAQUEUE_FFTRESULTS_LINEAR_SCALE_SMOOTH + 1 ) ,
        ZMEDIAQUEUE_FFTRESULTS_LOG_SCALE_SMOOTH	= ( ZMEDIAQUEUE_FFTRESULTS_LOG_SCALE_RAW + 1 ) ,
        _ZMEDIAQUEUE_FFTRESULTS_COUNT	= ( ZMEDIAQUEUE_FFTRESULTS_LOG_SCALE_SMOOTH + 1 ) 
    } 	ZMEDIAQUEUE_FFTRESULTS;

#define	ZMQ_PROPERTY_BUFFERING_TIME_DEFAULT	( 5 )

#define	ZMQ_PROPERTY_AUDIO_BALANCE_DEFAULT	( 10000 )

#define	ZMQ_PROPERTY_AUDIO_BALANCE_MAX	( 20000 )

#define	ZMQ_PROPERTY_AUDIO_BALANCE_OFFSET	( 10000 )

typedef 
enum _ZMEDIAQUEUE_AUDIOENDPOINT
    {
        ZMEDIAQUEUE_AUDIOENDPOINT_INVALID	= 0,
        ZMEDIAQUEUE_AUDIOENDPOINT_AUTO	= ( ZMEDIAQUEUE_AUDIOENDPOINT_INVALID + 1 ) ,
        ZMEDIAQUEUE_AUDIOENDPOINT_HEADSET	= ( ZMEDIAQUEUE_AUDIOENDPOINT_AUTO + 1 ) ,
        ZMEDIAQUEUE_AUDIOENDPOINT_SPEAKER	= ( ZMEDIAQUEUE_AUDIOENDPOINT_HEADSET + 1 ) ,
        _ZMEDIAQUEUE_AUDIOENDPOINT_COUNT	= ( ZMEDIAQUEUE_AUDIOENDPOINT_SPEAKER + 1 ) 
    } 	ZMEDIAQUEUE_AUDIOENDPOINT;

typedef 
enum _ZMEDIAQUEUE_RADIO_ANTENNATYPE
    {
        ZMEDIAQUEUE_RADIO_ANTENNATYPE_EXTERNAL	= 0,
        ZMEDIAQUEUE_RADIO_ANTENNATYPE_INTERNAL	= ( ZMEDIAQUEUE_RADIO_ANTENNATYPE_EXTERNAL + 1 ) 
    } 	ZMEDIAQUEUE_RADIO_ANTENNATYPE;

typedef 
enum _ZMEDIAQUEUE_PROPERTY
    {
        ZMQ_PROPERTY_FRAMES_PER_SECOND	= 0,
        ZMQ_PROPERTY_DROPPED_FRAMES	= ( ZMQ_PROPERTY_FRAMES_PER_SECOND + 1 ) ,
        ZMQ_PROPERTY_CAN_SEEK	= ( ZMQ_PROPERTY_DROPPED_FRAMES + 1 ) ,
        ZMQ_PROPERTY_CAN_PAUSE	= ( ZMQ_PROPERTY_CAN_SEEK + 1 ) ,
        ZMQ_PROPERTY_AUDIO_BALANCE	= ( ZMQ_PROPERTY_CAN_PAUSE + 1 ) ,
        ZMQ_PROPERTY_BUFFERING_TIME	= ( ZMQ_PROPERTY_AUDIO_BALANCE + 1 ) ,
        ZMQ_PROPERTY_BUFFERING_PROGRESS	= ( ZMQ_PROPERTY_BUFFERING_TIME + 1 ) ,
        ZMQ_PROPERTY_DOWNLOAD_PROGRESS	= ( ZMQ_PROPERTY_BUFFERING_PROGRESS + 1 ) ,
        ZMQ_PROPERTY_DROPPED_FRAMES_PER_SECOND	= ( ZMQ_PROPERTY_DOWNLOAD_PROGRESS + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_AUDIOROUTINGPREFERENCE	= ( ZMQ_PROPERTY_DROPPED_FRAMES_PER_SECOND + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_RADIO_ANTENNATYPE	= ( ZMEDIAQUEUE_PROPERTY_AUDIOROUTINGPREFERENCE + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_RADIO_ANTENNASTATUS	= ( ZMEDIAQUEUE_PROPERTY_RADIO_ANTENNATYPE + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_RADIO_SUSPEND_PLAYSTATE	= ( ZMEDIAQUEUE_PROPERTY_RADIO_ANTENNASTATUS + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_REBUILDINPROGRESS	= ( ZMEDIAQUEUE_PROPERTY_RADIO_SUSPEND_PLAYSTATE + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_MSSSTREAMING_ITEM	= ( ZMEDIAQUEUE_PROPERTY_REBUILDINPROGRESS + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_BACKGROUNDART_REFCOUNT	= ( ZMEDIAQUEUE_PROPERTY_MSSSTREAMING_ITEM + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_OWNER_PROCESSID	= ( ZMEDIAQUEUE_PROPERTY_BACKGROUNDART_REFCOUNT + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_PRODUCTID	= ( ZMEDIAQUEUE_PROPERTY_OWNER_PROCESSID + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_TITLE	= ( ZMEDIAQUEUE_PROPERTY_APP_PRODUCTID + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_ART	= ( ZMEDIAQUEUE_PROPERTY_APP_TITLE + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_ACTIVATION_URI	= ( ZMEDIAQUEUE_PROPERTY_APP_ART + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_CONTEXT	= ( ZMEDIAQUEUE_PROPERTY_APP_ACTIVATION_URI + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_APP_ACTIVATION_ARGS	= ( ZMEDIAQUEUE_PROPERTY_APP_CONTEXT + 1 ) ,
        ZMQ_PROPERTY_CAN_SETRATE	= ( ZMEDIAQUEUE_PROPERTY_APP_ACTIVATION_ARGS + 1 ) ,
        ZMEDIAQUEUE_PROPERTY_ENABLE_WINDOWLESS_SWAPCHAIN_MODE	= ( ZMQ_PROPERTY_CAN_SETRATE + 1 ) 
    } 	ZMEDIAQUEUE_PROPERTY;

typedef 
enum _ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_COUNT
    {
        ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_ZERO	= 0,
        ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_ONE	= ( ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_ZERO + 1 ) ,
        ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_MORE_THAN_ONE	= ( ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_ONE + 1 ) 
    } 	ZMEDIAQUEUE_CONNECTIVITY_PLAYABLE_COUNT;

typedef /* [public] */ struct __MIDL___MIDL_itf_zmediaqueuetypes_0000_0000_0001
    {
    HRESULT m_hrPlayback;
    char m_errorMsg[ 50 ];
    char m_url[ 300 ];
    SYSTEMTIME m_utcTime;
    char m_ethernetType[ 15 ];
    GUID m_mediaId;
    DWORD m_dwBufferingCount;
    char m_hostIP[ 20 ];
    DWORD m_dwInitialBufferingDuration;
    DWORD m_dwPlaybackStartDuration;
    DWORD m_dwStartMs;
    DWORD m_dwEndMs;
    } 	PlaybackTelemetryData;



extern RPC_IF_HANDLE __MIDL_itf_zmediaqueuetypes_0000_0000_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_zmediaqueuetypes_0000_0000_v0_0_s_ifspec;

/* Additional Prototypes for ALL interfaces */

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif


