/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name: UcmtcpciTraceEnums.h

Abstract:
    Generated trace enums

Environment:
    kernel mode only

--*/

#ifndef _UCMTCPCITRACEENUMS_H_
#define _UCMTCPCITRACEENUMS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

// begin_wpp config
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_ALERT_TYPE, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_ALERT_TYPE));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_IOCTL, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_IOCTL));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_CONTROL_TYPE, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_CONTROL_TYPE));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_PIN_ASSIGNMENT, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_PIN_ASSIGNMENT));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_HPD_STATUS, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_HPD_STATUS));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_DISPLAY_OUT_STATUS, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_DISPLAYPORT_DISPLAY_OUT_STATUS));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_COMMAND, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_COMMAND));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_RETRY_COUNTER, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_RETRY_COUNTER));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_TRANSMIT_SOP_MESSAGE, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_TRANSMIT_SOP_MESSAGE));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_VBUS_VOLTAGE_ALARM_LSB, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_VBUS_VOLTAGE_ALARM_LSB));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_VCONN_POWER_SUPPORTED, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_VCONN_POWER_SUPPORTED));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_RECEIVED_SOP_MESSAGE, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_RECEIVED_SOP_MESSAGE));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_VBUS_VOLTAGE_SCALE_FACTOR, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_VBUS_VOLTAGE_SCALE_FACTOR));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_MUX_CONTROL, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_MUX_CONTROL));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_ROLES_SUPPORTED, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_ROLES_SUPPORTED));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_SOURCE_RESISTOR_SUPPORTED, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_SOURCE_RESISTOR_SUPPORTED));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_MESSAGE_HEADER_PD_REVISION, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_MESSAGE_HEADER_PD_REVISION));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_ROLE_CONTROL_CC, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_ROLE_CONTROL_CC));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_ROLE_CONTROL_RP, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_ROLE_CONTROL_RP));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_CC_STATE, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_CC_STATE));
// CUSTOM_TYPE(UCMTCPCI_PORT_CONTROLLER_CC_STATUS_CONNECT_RESULT, ItemEnum(_UCMTCPCI_PORT_CONTROLLER_CC_STATUS_CONNECT_RESULT));
// end_wpp

WDF_EXTERN_C_END

#endif // _UCMTCPCITRACEENUMS_H_

