/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmTcpciGlobals.h

Abstract:

    UCM-TCPCI global definitions.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMTCPCIGLOBALS_H_
#define _UCMTCPCIGLOBALS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



typedef struct _UCMTCPCI_DRIVER_GLOBALS {
    ULONG Reserved;
} UCMTCPCI_DRIVER_GLOBALS, *PUCMTCPCI_DRIVER_GLOBALS;




WDF_EXTERN_C_END

#endif // _UCMTCPCIGLOBALS_H_

