/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmTcpciDevice.h

Abstract:

    Methods, callbacks, and structs for a UCM-TCPCI device.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCMTCPCIDEVICE_H_
#define _UCMTCPCIDEVICE_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START





typedef struct _UCMTCPCI_DEVICE_CONFIG
{
    ULONG Size;
} UCMTCPCI_DEVICE_CONFIG, *PUCMTCPCI_DEVICE_CONFIG;

VOID
FORCEINLINE
UCMTCPCI_DEVICE_CONFIG_INIT (
    _Out_ PUCMTCPCI_DEVICE_CONFIG Config
    )
{
    RtlZeroMemory(Config, sizeof(*Config));
    Config->Size = sizeof(*Config);
}

//
// UCMTCPCI Function: UcmTcpciDeviceInitInitialize
//
typedef
_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
WDFAPI
NTSTATUS
(*PFN_UCMTCPCIDEVICEINITINITIALIZE)(
    _In_
    PUCMTCPCI_DRIVER_GLOBALS DriverGlobals,
    _In_
    PWDFDEVICE_INIT DeviceInit
    );

_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
FORCEINLINE
UcmTcpciDeviceInitInitialize(
    _In_
    PWDFDEVICE_INIT DeviceInit
    )
{
    return ((PFN_UCMTCPCIDEVICEINITINITIALIZE) UcmtcpciFunctions[UcmTcpciDeviceInitInitializeTableIndex])(UcmtcpciDriverGlobals, DeviceInit);
}

//
// UCMTCPCI Function: UcmTcpciDeviceInitialize
//
typedef
_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
WDFAPI
NTSTATUS
(*PFN_UCMTCPCIDEVICEINITIALIZE)(
    _In_
    PUCMTCPCI_DRIVER_GLOBALS DriverGlobals,
    _In_
    WDFDEVICE WdfDevice,
    _In_
    PUCMTCPCI_DEVICE_CONFIG Config
    );

_Must_inspect_result_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
FORCEINLINE
UcmTcpciDeviceInitialize(
    _In_
    WDFDEVICE WdfDevice,
    _In_
    PUCMTCPCI_DEVICE_CONFIG Config
    )
{
    return ((PFN_UCMTCPCIDEVICEINITIALIZE) UcmtcpciFunctions[UcmTcpciDeviceInitializeTableIndex])(UcmtcpciDriverGlobals, WdfDevice, Config);
}



WDF_EXTERN_C_END

#endif // _UCMTCPCIDEVICE_H_

