/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcxClass.h

Abstract:

    This module contains the USB Host Controller (UCX) WDF class extension's datatypes and exported
    methods.

Environment:

    Kernel-mode only.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _UCXCLASS_H_
#define _UCXCLASS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



#ifndef WDFAPI
#error Include WDF.H first
#endif

#if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)

#include <ntintsafe.h>
#include <ntstrsafe.h>
#include <usbspec.h>
#include <usb.h>
#include <usbioctl.h>
#include <usbdlib.h>

typedef void (*PFN_UCXFUNC)(void);
extern PFN_UCXFUNC UcxFunctions[];

#include "UcxGlobals.h"
#include "UcxFuncEnum.h"
#include "UcxObjects.h"
#include "UcxController.h"
#include "UcxRootHub.h"
#include "UcxUsbDevice.h"
#include "UcxEndpoint.h"
#include "UcxSStreams.h"



//
// UCX Function: UcxInitializeDeviceInit
//
typedef
__drv_requiresIRQL(PASSIVE_LEVEL)
_Must_inspect_result_
WDFAPI
NTSTATUS
(*PFN_UCXINITIALIZEDEVICEINIT)(
    _In_
    PUCX_DRIVER_GLOBALS DriverGlobals,
    __inout
    PWDFDEVICE_INIT DeviceInit
    );

__drv_requiresIRQL(PASSIVE_LEVEL)
_Must_inspect_result_
NTSTATUS
FORCEINLINE
UcxInitializeDeviceInit(
    __inout
    PWDFDEVICE_INIT DeviceInit
    )
{
    return ((PFN_UCXINITIALIZEDEVICEINIT) UcxFunctions[UcxInitializeDeviceInitTableIndex])(UcxDriverGlobals, DeviceInit);
}



#endif // if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)

WDF_EXTERN_C_END

#endif // _UCXCLASS_H_


