/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UrsTypes.h

Abstract:

    URS type declarations.

Environment:

    Kernel-mode.

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _URSTYPES_H_
#define _URSTYPES_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



typedef enum _URS_HOST_INTERFACE_TYPE {
    UrsHostInterfaceTypeEhci = 0,
    UrsHostInterfaceTypeXhci,
    UrsHostInterfaceTypeOther,
} URS_HOST_INTERFACE_TYPE;

typedef enum _URS_ROLE {
    UrsRoleNone = 0,
    UrsRoleHost,
    UrsRoleFunction,
} URS_ROLE, *PURS_ROLE;

typedef enum _URS_HARDWARE_EVENT {
    UrsHardwareEventNone = 0, //  Internal use only. Must be zero.
    UrsHardwareEventDetach,
    UrsHardwareEventIdGround,
    UrsHardwareEventIdFloat,
    UrsHardwareEventPortTypeDfp,
    UrsHardwareEventPortTypeUfp,
} URS_HARDWARE_EVENT, *PURS_HARDWARE_EVENT;



DECLARE_HANDLE(URSIORESLIST);



WDF_EXTERN_C_END

#endif // _URSTYPES_H_

