/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmCx.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START


typedef VOID (*UCMFUNC) (VOID);
extern UCMFUNC UcmFunctions[];

#include "UcmTypes.h"
#include "UcmGlobals.h"
#include "UcmFuncEnum.h"
#include "UcmManager.h"

WDF_EXTERN_C_END

