/*++

Copyright (c) Microsoft Corporation. All rights reserved.

Module Name:

    UcmGlobals.h

Environment:

    user mode

NOTE: This header is generated by stubwork.

      To modify contents, add or remove <shared> or <umdf>
      tags in the corresponding .x and .y template files.

--*/

#pragma once

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START


typedef struct _UCM_DRIVER_GLOBALS {
    ULONG Reserved;
} UCM_DRIVER_GLOBALS, *PUCM_DRIVER_GLOBALS;

WDF_EXTERN_C_END

