/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

Module Name:

    NetAdapterDriver.h

Abstract:

    This is the interfaces for the NetAdapterDriver

Environment:

    kernel mode only

Revision History:

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _NETADAPTERDRIVER_H_
#define _NETADAPTERDRIVER_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START


typedef enum _NET_ADAPTER_DRIVER_TYPE {
    NET_ADAPTER_DRIVER_TYPE_INVALID = 0,
    NET_ADAPTER_DRIVER_TYPE_MINIPORT,
} NET_ADAPTER_DRIVER_TYPE;



//
// NET Function: NetAdapterDriverWdmGetHandle
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_HANDLE
(*PFN_NETADAPTERDRIVERWDMGETHANDLE)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    WDFDRIVER Driver,
    _In_
    NET_ADAPTER_DRIVER_TYPE Type
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
NDIS_HANDLE
FORCEINLINE
NetAdapterDriverWdmGetHandle(
    _In_
    WDFDRIVER Driver,
    _In_
    NET_ADAPTER_DRIVER_TYPE Type
    )
{
    return ((PFN_NETADAPTERDRIVERWDMGETHANDLE) NetFunctions[NetAdapterDriverWdmGetHandleTableIndex])(NetDriverGlobals, Driver, Type);
}



WDF_EXTERN_C_END

#endif // _NETADAPTERDRIVER_H_

